/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './discover';
import * as import1 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import10 from '@angular/core/src/linker/component_factory';
export declare class Wrapper_DiscoverPage {
    context: import0.DiscoverPage;
    changed: boolean;
    constructor(p0: any);
    detectChangesInternal(view: import1.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare const DiscoverPageNgFactory: import10.ComponentFactory<import0.DiscoverPage>;
export declare function viewFactory_DiscoverPage0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import3.AppElement): import1.AppView<import0.DiscoverPage>;
