/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './message-item';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/linker/component_factory';
export declare class Wrapper_DoMssageItem {
    context: import0.DoMssageItem;
    changed: boolean;
    _message: any;
    constructor();
    check_message(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare const DoMssageItemNgFactory: import9.ComponentFactory<import0.DoMssageItem>;
export declare function viewFactory_DoMssageItem0(viewUtils: import2.ViewUtils, parentInjector: import6.Injector, declarationEl: import5.AppElement): import3.AppView<import0.DoMssageItem>;
