/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './do-chat-header';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
export class Wrapper_DoChatHeader {
  context:import0.DoChatHeader;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.DoChatHeader();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_DoChatHeader_Host:import2.RenderComponentType = (null as any);
class _View_DoChatHeader_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _DoChatHeader_0_4:Wrapper_DoChatHeader;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DoChatHeader_Host0,renderType_DoChatHeader_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('do-chat-header',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DoChatHeader0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoChatHeader_0_4 = new Wrapper_DoChatHeader();
    this._appEl_0.initComponent(this._DoChatHeader_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DoChatHeader_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DoChatHeader) && (0 === requestNodeIndex))) { return this._DoChatHeader_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DoChatHeader_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoChatHeader_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_DoChatHeader_Host === (null as any))) { (renderType_DoChatHeader_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DoChatHeader_Host0(viewUtils,parentInjector,declarationEl);
}
export const DoChatHeaderNgFactory:import9.ComponentFactory<import0.DoChatHeader> = new import9.ComponentFactory<import0.DoChatHeader>('do-chat-header',viewFactory_DoChatHeader_Host0,import0.DoChatHeader);
const styles_DoChatHeader:any[] = ([] as any[]);
var renderType_DoChatHeader:import2.RenderComponentType = (null as any);
class _View_DoChatHeader0 extends import1.AppView<import0.DoChatHeader> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DoChatHeader0,renderType_DoChatHeader,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','chat-header clearfix');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'alt','avatar');
    this.renderer.setElementAttribute(this._el_2,'src','https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_01_green.jpg');
    this._text_3 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','chat-about');
    this._text_5 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','chat-with');
    this._text_7 = this.renderer.createText(this._el_6,'Chat with Vincent Porter',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','chat-num-messages');
    this._text_10 = this.renderer.createText(this._el_9,'already 1 902 messages',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n	',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'i',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','fa fa-star');
    this._text_14 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_DoChatHeader0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.DoChatHeader> {
  if ((renderType_DoChatHeader === (null as any))) { (renderType_DoChatHeader = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_DoChatHeader,{})); }
  return new _View_DoChatHeader0(viewUtils,parentInjector,declarationEl);
}