/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './chat';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/navbar/navbar';
import * as import15 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import16 from 'ionic-angular/components/content/content';
import * as import17 from '../../components/lc-chat/lc-chat';
import * as import18 from '../../components/lc-input-box/lc-input-box';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/navigation/view-controller';
import * as import22 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import23 from 'ionic-angular/components/app/app';
import * as import24 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import26 from 'ionic-angular/util/keyboard';
import * as import27 from '@angular/core/src/zone/ng_zone';
import * as import28 from 'ionic-angular/components/tabs/tabs';
import * as import29 from '../../components/lc-chat/lc-chat.ngfactory';
import * as import30 from 'ionic-angular/util/events';
import * as import31 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import32 from '../../components/lc-input-box/lc-input-box.ngfactory';
var renderType_ChatPage_Host:import0.RenderComponentType = (null as any);
class _View_ChatPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ChatPage_0_4:import3.ChatPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ChatPage_Host0,renderType_ChatPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-chat',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ChatPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ChatPage_0_4 = new import3.ChatPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams));
    this._appEl_0.initComponent(this._ChatPage_0_4,([] as any[]),compView_0);
    compView_0.create(this._ChatPage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ChatPage) && (0 === requestNodeIndex))) { return this._ChatPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ChatPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ChatPage_Host === (null as any))) { (renderType_ChatPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ChatPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ChatPageNgFactory:import11.ComponentFactory<import3.ChatPage> = new import11.ComponentFactory<import3.ChatPage>('page-chat',viewFactory_ChatPage_Host0,import3.ChatPage);
const styles_ChatPage:any[] = ([] as any[]);
var renderType_ChatPage:import0.RenderComponentType = (null as any);
class _View_ChatPage0 extends import1.AppView<import3.ChatPage> {
  _viewQuery_Content_0:import12.QueryList<any>;
  _text_0:any;
  _el_1:any;
  _Header_1_3:import13.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import14.Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ToolbarTitle_5_4:import15.ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Content_10_4:import16.Content;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _LCChat_12_4:import17.LCChat;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _Footer_15_3:import13.Footer;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Toolbar_17_4:import13.Toolbar;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _LCInputBox_19_4:import18.LCInputBox;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ChatPage0,renderType_ChatPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Content_0 = new import12.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import13.Header(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import21.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n	',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import22.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import14.Navbar(this.parentInjector.get(import23.App),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import2.AppElement(5,3,this,this._el_5);
    var compView_5:any = import24.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import15.ToolbarTitle(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_3_4);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'',(null as any));
    compView_5.create(this._ToolbarTitle_5_4,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_3.create(this._Navbar_3_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'id','chatContent');
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import2.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import25.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import16.Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import26.Keyboard),this.parentInjector.get(import27.NgZone),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import28.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'lc-chat',(null as any));
    this._appEl_12 = new import2.AppElement(12,10,this,this._el_12);
    var compView_12:any = import29.viewFactory_LCChat0(this.viewUtils,this.injector(12),this._appEl_12);
    this._LCChat_12_4 = new import17.LCChat(this.parentInjector.get(import30.Events),compView_12.ref);
    this._appEl_12.initComponent(this._LCChat_12_4,([] as any[]),compView_12);
    compView_12.create(this._LCChat_12_4,([] as any[]),(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_13
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_15 = this.renderer.createElement(parentRenderNode,'ion-footer',(null as any));
    this._Footer_15_3 = new import13.Footer(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import21.ViewController,(null as any)));
    this._text_16 = this.renderer.createText(this._el_15,'\n	',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','toolbar');
    this._appEl_17 = new import2.AppElement(17,15,this,this._el_17);
    var compView_17:any = import31.viewFactory_Toolbar0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Toolbar_17_4 = new import13.Toolbar(this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_17),this.renderer);
    this._appEl_17.initComponent(this._Toolbar_17_4,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'lc-input-box',(null as any));
    this._appEl_19 = new import2.AppElement(19,17,this,this._el_19);
    var compView_19:any = import32.viewFactory_LCInputBox0(this.viewUtils,this.injector(19),this._appEl_19);
    this._LCInputBox_19_4 = new import18.LCInputBox(this.parentInjector.get(import30.Events));
    this._appEl_19.initComponent(this._LCInputBox_19_4,([] as any[]),compView_19);
    compView_19.create(this._LCInputBox_19_4,([] as any[]),(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_17.create(this._Toolbar_17_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_20
      ]
      )
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'onMsg',this.eventHandler(this._handle_onMsg_12_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    const subscription_0:any = this._LCChat_12_4.onMsg.subscribe(this.eventHandler(this._handle_onMsg_12_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._viewQuery_Content_0.reset([this._Content_10_4]);
    this.context.chatContent = this._viewQuery_Content_0.first;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4; }
    if (((token === import14.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4; }
    if (((token === import13.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3; }
    if (((token === import17.LCChat) && (12 === requestNodeIndex))) { return this._LCChat_12_4; }
    if (((token === import16.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Content_10_4; }
    if (((token === import18.LCInputBox) && (19 === requestNodeIndex))) { return this._LCInputBox_19_4; }
    if (((token === import13.Toolbar) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Toolbar_17_4; }
    if (((token === import13.Footer) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Footer_15_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_10_4.ngOnInit(); }
    const currVal_5:any = this.context.convId;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._LCChat_12_4.convId = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.context.convName;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._LCChat_12_4.convName = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_8:any = this.context.convId;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._LCInputBox_19_4.convId = currVal_8;
      this._expr_8 = currVal_8;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.convName,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_6,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = this._Toolbar_17_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.ngOnDestroy();
  }
  private _handle_onMsg_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onMessage($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ChatPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ChatPage> {
  if ((renderType_ChatPage === (null as any))) { (renderType_ChatPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_ChatPage,{})); }
  return new _View_ChatPage0(viewUtils,parentInjector,declarationEl);
}