/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './do-contact-item';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/linker/component_factory';
export declare class Wrapper_DoContactItem {
    context: import0.DoContactItem;
    changed: boolean;
    _friendId: any;
    _friendName: any;
    _avatarUrl: any;
    constructor();
    check_friendId(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_friendName(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_avatarUrl(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare const DoContactItemNgFactory: import9.ComponentFactory<import0.DoContactItem>;
export declare function viewFactory_DoContactItem0(viewUtils: import2.ViewUtils, parentInjector: import6.Injector, declarationEl: import5.AppElement): import3.AppView<import0.DoContactItem>;
