/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './do-contact-detail';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '../../providers/data-service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/note/note.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/thumbnail/thumbnail.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/gestures/gesture-controller';
import * as import23 from 'ionic-angular/util/form';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/common/src/directives/ng_if';
import * as import26 from 'ionic-angular/components/avatar/avatar';
import * as import27 from 'ionic-angular/components/item/item';
import * as import28 from 'ionic-angular/components/label/label';
import * as import29 from 'ionic-angular/components/note/note';
import * as import30 from 'ionic-angular/components/thumbnail/thumbnail';
import * as import31 from 'ionic-angular/components/button/button';
import * as import32 from 'ionic-angular/components/list/list';
import * as import33 from '@angular/core/src/security';
import * as import34 from '../text-img/color-generator';
import * as import35 from '../text-img/text-img.ngfactory';
import * as import36 from '../text-img/text-img';
import * as import37 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import38 from 'ionic-angular/components/icon/icon';
export class Wrapper_DoContactDetail {
  context:import0.DoContactDetail;
  changed:boolean;
  /*private*/ _clientId:any;
  constructor(p0:any) {
    this.changed = false;
    this._clientId = import1.UNINITIALIZED;
    this.context = new import0.DoContactDetail(p0);
  }
  check_clientId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._clientId,currValue))) {
      this.changed = true;
      this.context.clientId = currValue;
      this._clientId = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_DoContactDetail_Host:import4.RenderComponentType = (null as any);
class _View_DoContactDetail_Host0 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _DoContactDetail_0_4:Wrapper_DoContactDetail;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactDetail_Host0,renderType_DoContactDetail_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('do-contact-detail',rootSelector,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DoContactDetail0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoContactDetail_0_4 = new Wrapper_DoContactDetail(this.parentInjector.get(import8.DoDataService));
    this._appEl_0.initComponent(this._DoContactDetail_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DoContactDetail_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DoContactDetail) && (0 === requestNodeIndex))) { return this._DoContactDetail_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DoContactDetail_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoContactDetail_Host0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  if ((renderType_DoContactDetail_Host === (null as any))) { (renderType_DoContactDetail_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DoContactDetail_Host0(viewUtils,parentInjector,declarationEl);
}
export const DoContactDetailNgFactory:import10.ComponentFactory<import0.DoContactDetail> = new import10.ComponentFactory<import0.DoContactDetail>('do-contact-detail',viewFactory_DoContactDetail_Host0,import0.DoContactDetail);
const styles_DoContactDetail:any[] = ([] as any[]);
var renderType_DoContactDetail:import4.RenderComponentType = (null as any);
class _View_DoContactDetail0 extends import3.AppView<import0.DoContactDetail> {
  _el_0:any;
  _List_0_3:import11.Wrapper_List;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import5.AppElement;
  _Item_2_4:import12.Wrapper_Item;
  _ItemContent_2_5:import12.Wrapper_ItemContent;
  _query_Label_2_0:import13.QueryList<any>;
  _query_Button_2_1:import13.QueryList<any>;
  _query_Icon_2_2:import13.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Avatar_4_3:import14.Wrapper_Avatar;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import5.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import15.Wrapper_NgIf;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import5.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import15.Wrapper_NgIf;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import5.AppElement;
  _TemplateRef_20_5:any;
  _NgIf_20_6:import15.Wrapper_NgIf;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import5.AppElement;
  _Item_23_4:import12.Wrapper_Item;
  _query_Label_23_0:import13.QueryList<any>;
  _query_Button_23_1:import13.QueryList<any>;
  _query_Icon_23_2:import13.QueryList<any>;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import5.AppElement;
  _Item_25_4:import12.Wrapper_Item;
  _ItemContent_25_5:import12.Wrapper_ItemContent;
  _query_Label_25_0:import13.QueryList<any>;
  _query_Button_25_1:import13.QueryList<any>;
  _query_Icon_25_2:import13.QueryList<any>;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import5.AppElement;
  _Item_28_4:import12.Wrapper_Item;
  _query_Label_28_0:import13.QueryList<any>;
  _query_Button_28_1:import13.QueryList<any>;
  _query_Icon_28_2:import13.QueryList<any>;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import5.AppElement;
  _Item_30_4:import12.Wrapper_Item;
  _ItemContent_30_5:import12.Wrapper_ItemContent;
  _query_Label_30_0:import13.QueryList<any>;
  _query_Button_30_1:import13.QueryList<any>;
  _query_Icon_30_2:import13.QueryList<any>;
  _text_31:any;
  _el_32:any;
  _Label_32_3:import16.Wrapper_Label;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _Note_35_3:import17.Wrapper_Note;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import5.AppElement;
  _Item_39_4:import12.Wrapper_Item;
  _ItemContent_39_5:import12.Wrapper_ItemContent;
  _query_Label_39_0:import13.QueryList<any>;
  _query_Button_39_1:import13.QueryList<any>;
  _query_Icon_39_2:import13.QueryList<any>;
  _text_40:any;
  _el_41:any;
  _Label_41_3:import16.Wrapper_Label;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _Thumbnail_44_3:import18.Wrapper_Thumbnail;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _Thumbnail_49_3:import18.Wrapper_Thumbnail;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _Thumbnail_54_3:import18.Wrapper_Thumbnail;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  /*private*/ _appEl_60:import5.AppElement;
  _Button_60_4:import19.Wrapper_Button;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  /*private*/ _appEl_63:import5.AppElement;
  _Button_63_4:import19.Wrapper_Button;
  _text_64:any;
  _text_65:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactDetail0,renderType_DoContactDetail,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-list',(null as any));
    this._List_0_3 = new import11.Wrapper_List(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import22.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'detail-none','');
    this.renderer.setElementAttribute(this._el_2,'no-lines','');
    this._appEl_2 = new import5.AppElement(2,0,this,this._el_2);
    var compView_2:any = import12.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import12.Wrapper_Item(this.parentInjector.get(import23.Form),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import12.Wrapper_ItemContent();
    this._query_Label_2_0 = new import13.QueryList<any>();
    this._query_Button_2_1 = new import13.QueryList<any>();
    this._query_Icon_2_2 = new import13.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Avatar_4_3 = new import14.Wrapper_Avatar();
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_6 = new import5.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import24.TemplateRef_(this._appEl_6,viewFactory_DoContactDetail1);
    this._NgIf_6_6 = new import15.Wrapper_NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_8 = new import5.AppElement(8,4,this,this._anchor_8);
    this._TemplateRef_8_5 = new import24.TemplateRef_(this._appEl_8,viewFactory_DoContactDetail2);
    this._NgIf_8_6 = new import15.Wrapper_NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_20 = new import5.AppElement(20,2,this,this._anchor_20);
    this._TemplateRef_20_5 = new import24.TemplateRef_(this._appEl_20,viewFactory_DoContactDetail3);
    this._NgIf_20_6 = new import15.Wrapper_NgIf(this._appEl_20.vcRef,this._TemplateRef_20_5);
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_16,
        this._el_17,
        this._text_19,
        this._text_21
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._appEl_20])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_0,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','lcdivider item');
    this._appEl_23 = new import5.AppElement(23,0,this,this._el_23);
    var compView_23:any = import12.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import12.Wrapper_Item(this.parentInjector.get(import23.Form),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_23),this.renderer);
    this._query_Label_23_0 = new import13.QueryList<any>();
    this._query_Button_23_1 = new import13.QueryList<any>();
    this._query_Icon_23_2 = new import13.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4.context,([] as any[]),compView_23);
    this._query_Label_23_0.reset(([] as any[]));
    this._Item_23_4.context.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item item-block');
    this.renderer.setElementAttribute(this._el_25,'detail-none','');
    this.renderer.setElementAttribute(this._el_25,'ion-item','');
    this.renderer.setElementAttribute(this._el_25,'no-lines','');
    this._appEl_25 = new import5.AppElement(25,0,this,this._el_25);
    var compView_25:any = import12.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import12.Wrapper_Item(this.parentInjector.get(import23.Form),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_25),this.renderer);
    this._ItemContent_25_5 = new import12.Wrapper_ItemContent();
    this._query_Label_25_0 = new import13.QueryList<any>();
    this._query_Button_25_1 = new import13.QueryList<any>();
    this._query_Icon_25_2 = new import13.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'设置备注和标签',(null as any));
    this._query_Label_25_0.reset(([] as any[]));
    this._Item_25_4.context.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_26]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_0,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','lcdivider item');
    this._appEl_28 = new import5.AppElement(28,0,this,this._el_28);
    var compView_28:any = import12.viewFactory_Item0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Item_28_4 = new import12.Wrapper_Item(this.parentInjector.get(import23.Form),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_28),this.renderer);
    this._query_Label_28_0 = new import13.QueryList<any>();
    this._query_Button_28_1 = new import13.QueryList<any>();
    this._query_Icon_28_2 = new import13.QueryList<any>();
    this._appEl_28.initComponent(this._Item_28_4.context,([] as any[]),compView_28);
    this._query_Label_28_0.reset(([] as any[]));
    this._Item_28_4.context.contentLabel = this._query_Label_28_0.first;
    compView_28.create(this._Item_28_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','item item-block');
    this._appEl_30 = new import5.AppElement(30,0,this,this._el_30);
    var compView_30:any = import12.viewFactory_Item0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Item_30_4 = new import12.Wrapper_Item(this.parentInjector.get(import23.Form),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_30),this.renderer);
    this._ItemContent_30_5 = new import12.Wrapper_ItemContent();
    this._query_Label_30_0 = new import13.QueryList<any>();
    this._query_Button_30_1 = new import13.QueryList<any>();
    this._query_Icon_30_2 = new import13.QueryList<any>();
    this._appEl_30.initComponent(this._Item_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','stacked');
    this.renderer.setElementAttribute(this._el_32,'item-left','');
    this._Label_32_3 = new import16.Wrapper_Label(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_32),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'地区',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_35,'item-left','');
    this._Note_35_3 = new import17.Wrapper_Note();
    this._text_36 = this.renderer.createText(this._el_35,'',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_30_0.reset([this._Label_32_3.context]);
    this._Item_30_4.context.contentLabel = this._query_Label_30_0.first;
    compView_30.create(this._Item_30_4.context,[
      ([] as any[]).concat([
        this._el_32,
        this._el_35
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_31,
        this._text_34,
        this._text_37
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','item item-block');
    this.renderer.setElementAttribute(this._el_39,'detail-none','');
    this.renderer.setElementAttribute(this._el_39,'ion-item','');
    this.renderer.setElementAttribute(this._el_39,'no-lines','');
    this._appEl_39 = new import5.AppElement(39,0,this,this._el_39);
    var compView_39:any = import12.viewFactory_Item0(this.viewUtils,this.injector(39),this._appEl_39);
    this._Item_39_4 = new import12.Wrapper_Item(this.parentInjector.get(import23.Form),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_39),this.renderer);
    this._ItemContent_39_5 = new import12.Wrapper_ItemContent();
    this._query_Label_39_0 = new import13.QueryList<any>();
    this._query_Button_39_1 = new import13.QueryList<any>();
    this._query_Icon_39_2 = new import13.QueryList<any>();
    this._appEl_39.initComponent(this._Item_39_4.context,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','stacked');
    this.renderer.setElementAttribute(this._el_41,'item-left','');
    this._Label_41_3 = new import16.Wrapper_Label(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_41),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'个人相册',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_44,'item-left','');
    this._Thumbnail_44_3 = new import18.Wrapper_Thumbnail();
    this._text_45 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'img',(null as any));
    this.renderer.setElementAttribute(this._el_46,'src','assets/img/advance-card-alaska.jpg');
    this._text_47 = this.renderer.createText(this._el_44,'\n        ',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_49 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_49,'item-left','');
    this._Thumbnail_49_3 = new import18.Wrapper_Thumbnail();
    this._text_50 = this.renderer.createText(this._el_49,'\n            ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'img',(null as any));
    this.renderer.setElementAttribute(this._el_51,'src','assets/img/advance-card-bttf.png');
    this._text_52 = this.renderer.createText(this._el_49,'\n        ',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_54,'item-left','');
    this._Thumbnail_54_3 = new import18.Wrapper_Thumbnail();
    this._text_55 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'img',(null as any));
    this.renderer.setElementAttribute(this._el_56,'src','assets/img/advance-card-london.jpg');
    this._text_57 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_39_0.reset([this._Label_41_3.context]);
    this._Item_39_4.context.contentLabel = this._query_Label_39_0.first;
    compView_39.create(this._Item_39_4.context,[
      ([] as any[]).concat([
        this._el_41,
        this._el_44,
        this._el_49,
        this._el_54
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_40,
        this._text_43,
        this._text_48,
        this._text_53,
        this._text_58
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_59 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_60,'block','');
    this.renderer.setElementAttribute(this._el_60,'color','weixinGreen');
    this.renderer.setElementAttribute(this._el_60,'ion-button','');
    this._appEl_60 = new import5.AppElement(60,0,this,this._el_60);
    var compView_60:any = import19.viewFactory_Button0(this.viewUtils,this.injector(60),this._appEl_60);
    this._Button_60_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_60),this.renderer);
    this._appEl_60.initComponent(this._Button_60_4.context,([] as any[]),compView_60);
    this._text_61 = this.renderer.createText((null as any),'发消息',(null as any));
    compView_60.create(this._Button_60_4.context,[([] as any[]).concat([this._text_61])],(null as any));
    this._text_62 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_63,'block','');
    this.renderer.setElementAttribute(this._el_63,'color','light');
    this.renderer.setElementAttribute(this._el_63,'ion-button','');
    this._appEl_63 = new import5.AppElement(63,0,this,this._el_63);
    var compView_63:any = import19.viewFactory_Button0(this.viewUtils,this.injector(63),this._appEl_63);
    this._Button_63_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_63),this.renderer);
    this._appEl_63.initComponent(this._Button_63_4.context,([] as any[]),compView_63);
    this._text_64 = this.renderer.createText((null as any),'视频聊天',(null as any));
    compView_63.create(this._Button_63_4.context,[([] as any[]).concat([this._text_64])],(null as any));
    this._text_65 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_25,'click',this.eventHandler(this._handle_click_25_0.bind(this)));
    this._expr_7 = import1.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_60,'click',this.eventHandler(this._handle_click_60_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_63,'click',this.eventHandler(this._handle_click_63_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import25.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6.context; }
    if (((token === import24.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import25.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6.context; }
    if (((token === import26.Avatar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Avatar_4_3.context; }
    if (((token === import24.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import25.NgIf) && (20 === requestNodeIndex))) { return this._NgIf_20_6.context; }
    if (((token === import27.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_2_4.context; }
    if (((token === import27.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_2_5.context; }
    if (((token === import27.Item) && (23 === requestNodeIndex))) { return this._Item_23_4.context; }
    if (((token === import27.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_25_4.context; }
    if (((token === import27.ItemContent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_25_5.context; }
    if (((token === import27.Item) && (28 === requestNodeIndex))) { return this._Item_28_4.context; }
    if (((token === import28.Label) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Label_32_3.context; }
    if (((token === import29.Note) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Note_35_3.context; }
    if (((token === import27.Item) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Item_30_4.context; }
    if (((token === import27.ItemContent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ItemContent_30_5.context; }
    if (((token === import28.Label) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Label_41_3.context; }
    if (((token === import30.Thumbnail) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Thumbnail_44_3.context; }
    if (((token === import30.Thumbnail) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Thumbnail_49_3.context; }
    if (((token === import30.Thumbnail) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Thumbnail_54_3.context; }
    if (((token === import27.Item) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Item_39_4.context; }
    if (((token === import27.ItemContent) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._ItemContent_39_5.context; }
    if (((token === import31.Button) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Button_60_4.context; }
    if (((token === import31.Button) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Button_63_4.context; }
    if (((token === import32.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._List_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._List_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Avatar_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_0:any = this.context.avatar;
    this._NgIf_6_6.check_ngIf(currVal_0,throwOnChange,false);
    this._NgIf_6_6.detectChangesInternal(this,this._anchor_6,throwOnChange);
    const currVal_1:boolean = (!this.context.avatar || (0 === this.context.avatar.length));
    this._NgIf_8_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_8_6.detectChangesInternal(this,this._anchor_8,throwOnChange);
    const currVal_5:any = this.context.isStared;
    this._NgIf_20_6.check_ngIf(currVal_5,throwOnChange,false);
    this._NgIf_20_6.detectChangesInternal(this,this._anchor_20,throwOnChange);
    if (this._Item_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    if (this._Item_25_4.detectChangesInternal(this,this._el_25,throwOnChange)) { this._appEl_25.componentView.markAsCheckOnce(); }
    this._ItemContent_25_5.detectChangesInternal(this,this._el_25,throwOnChange);
    if (this._Item_28_4.detectChangesInternal(this,this._el_28,throwOnChange)) { this._appEl_28.componentView.markAsCheckOnce(); }
    if (this._Item_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    this._ItemContent_30_5.detectChangesInternal(this,this._el_30,throwOnChange);
    this._Label_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    this._Note_35_3.detectChangesInternal(this,this._el_35,throwOnChange);
    if (this._Item_39_4.detectChangesInternal(this,this._el_39,throwOnChange)) { this._appEl_39.componentView.markAsCheckOnce(); }
    this._ItemContent_39_5.detectChangesInternal(this,this._el_39,throwOnChange);
    this._Label_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    this._Thumbnail_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    this._Thumbnail_49_3.detectChangesInternal(this,this._el_49,throwOnChange);
    this._Thumbnail_54_3.detectChangesInternal(this,this._el_54,throwOnChange);
    const currVal_9:any = '';
    this._Button_60_4.check_block(currVal_9,throwOnChange,false);
    const currVal_10:any = 'weixinGreen';
    this._Button_60_4.check_color(currVal_10,throwOnChange,false);
    if (this._Button_60_4.detectChangesInternal(this,this._el_60,throwOnChange)) { this._appEl_60.componentView.markAsCheckOnce(); }
    const currVal_12:any = '';
    this._Button_63_4.check_block(currVal_12,throwOnChange,false);
    const currVal_13:any = 'light';
    this._Button_63_4.check_color(currVal_13,throwOnChange,false);
    if (this._Button_63_4.detectChangesInternal(this,this._el_63,throwOnChange)) { this._appEl_63.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
          this._query_Icon_2_2.reset([this._appEl_20.mapNestedViews(_View_DoContactDetail3,(nestedView:_View_DoContactDetail3):any => {
            return [nestedView._Icon_0_3.context];
        })]);
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4.context._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset(([] as any[]));
        this._Item_23_4.context._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset(([] as any[]));
        this._Item_25_4.context._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset(([] as any[]));
        this._Item_25_4.context._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if (this._query_Button_28_1.dirty) {
        this._query_Button_28_1.reset(([] as any[]));
        this._Item_28_4.context._buttons = this._query_Button_28_1;
        this._query_Button_28_1.notifyOnChanges();
      }
      if (this._query_Icon_28_2.dirty) {
        this._query_Icon_28_2.reset(([] as any[]));
        this._Item_28_4.context._icons = this._query_Icon_28_2;
        this._query_Icon_28_2.notifyOnChanges();
      }
      if (this._query_Button_30_1.dirty) {
        this._query_Button_30_1.reset(([] as any[]));
        this._Item_30_4.context._buttons = this._query_Button_30_1;
        this._query_Button_30_1.notifyOnChanges();
      }
      if (this._query_Icon_30_2.dirty) {
        this._query_Icon_30_2.reset(([] as any[]));
        this._Item_30_4.context._icons = this._query_Icon_30_2;
        this._query_Icon_30_2.notifyOnChanges();
      }
      if (this._query_Button_39_1.dirty) {
        this._query_Button_39_1.reset(([] as any[]));
        this._Item_39_4.context._buttons = this._query_Button_39_1;
        this._query_Button_39_1.notifyOnChanges();
      }
      if (this._query_Icon_39_2.dirty) {
        this._query_Icon_39_2.reset(([] as any[]));
        this._Item_39_4.context._icons = this._query_Icon_39_2;
        this._query_Icon_39_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_25_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_28_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_30_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_39_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_60_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_63_4.context.ngAfterContentInit(); }
    }
    const currVal_2:any = import2.interpolate(1,'',this.context.markName,'');
    if (import2.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_12,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import2.interpolate(1,'用户ID：',this.context.clientId,'');
    if (import2.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_15,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import2.interpolate(1,'昵称：',this.context.nickName,'');
    if (import2.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_18,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = import2.interpolate(1,'\n            ',this.context.location,'\n        ');
    if (import2.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_36,currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.navToSetTags($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_60_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.navToChat($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_63_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.navToChat($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DoContactDetail0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<import0.DoContactDetail> {
  if ((renderType_DoContactDetail === (null as any))) { (renderType_DoContactDetail = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_DoContactDetail,{})); }
  return new _View_DoContactDetail0(viewUtils,parentInjector,declarationEl);
}
class _View_DoContactDetail1 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactDetail1,renderType_DoContactDetail,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','fixed');
    this._expr_0 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.avatar;
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import33.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoContactDetail1(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoContactDetail1(viewUtils,parentInjector,declarationEl);
}
class _View_DoContactDetail2 extends import3.AppView<any> {
  _el_0:any;
  _ColorGenerator_0_3:import34.ColorGenerator;
  _TextImage_0_4:import35.Wrapper_TextImage;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactDetail2,renderType_DoContactDetail,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'text-img',(null as any));
    this._ColorGenerator_0_3 = new import34.ColorGenerator();
    this._TextImage_0_4 = new import35.Wrapper_TextImage(new import21.ElementRef(this._el_0),this._ColorGenerator_0_3);
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.ColorGenerator) && (0 === requestNodeIndex))) { return this._ColorGenerator_0_3; }
    if (((token === import36.TextImage) && (0 === requestNodeIndex))) { return this._TextImage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.nickName;
    this._TextImage_0_4.check_text(currVal_0,throwOnChange,false);
    this._TextImage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoContactDetail2(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoContactDetail2(viewUtils,parentInjector,declarationEl);
}
class _View_DoContactDetail3 extends import3.AppView<any> {
  _el_0:any;
  _Icon_0_3:import37.Wrapper_Icon;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactDetail3,renderType_DoContactDetail,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','weixinOrange');
    this.renderer.setElementAttribute(this._el_0,'item-right','');
    this.renderer.setElementAttribute(this._el_0,'name','star');
    this.renderer.setElementAttribute(this._el_0,'role','img');
    this._Icon_0_3 = new import37.Wrapper_Icon(this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._expr_2 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.Icon) && (0 === requestNodeIndex))) { return this._Icon_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'weixinOrange';
    this._Icon_0_3.check_color(currVal_0,throwOnChange,false);
    const currVal_1:any = 'star';
    this._Icon_0_3.check_name(currVal_1,throwOnChange,false);
    this._Icon_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Icon_0_3.context._hidden;
    if (import2.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_DoContactDetail0>this.parent)._query_Icon_2_2.setDirty();
  }
  destroyInternal():void {
    this._Icon_0_3.context.ngOnDestroy();
  }
}
function viewFactory_DoContactDetail3(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoContactDetail3(viewUtils,parentInjector,declarationEl);
}