/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './do-contact-item';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from 'ionic-angular/util/form';
import * as import15 from 'ionic-angular/config/config';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from 'ionic-angular/components/avatar/avatar';
import * as import20 from 'ionic-angular/components/item/item';
import * as import21 from '@angular/core/src/security';
import * as import22 from '../text-img/color-generator';
import * as import23 from '../text-img/text-img.ngfactory';
import * as import24 from '../text-img/text-img';
export class Wrapper_DoContactItem {
  context:import0.DoContactItem;
  changed:boolean;
  /*private*/ _friendId:any;
  /*private*/ _friendName:any;
  /*private*/ _avatarUrl:any;
  constructor() {
    this.changed = false;
    this._friendId = import1.UNINITIALIZED;
    this._friendName = import1.UNINITIALIZED;
    this._avatarUrl = import1.UNINITIALIZED;
    this.context = new import0.DoContactItem();
  }
  check_friendId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._friendId,currValue))) {
      this.changed = true;
      this.context.friendId = currValue;
      this._friendId = currValue;
    }
  }
  check_friendName(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._friendName,currValue))) {
      this.changed = true;
      this.context.friendName = currValue;
      this._friendName = currValue;
    }
  }
  check_avatarUrl(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._avatarUrl,currValue))) {
      this.changed = true;
      this.context.avatarUrl = currValue;
      this._avatarUrl = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_DoContactItem_Host:import4.RenderComponentType = (null as any);
class _View_DoContactItem_Host0 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _DoContactItem_0_4:Wrapper_DoContactItem;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactItem_Host0,renderType_DoContactItem_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('do-contact-item',rootSelector,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DoContactItem0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoContactItem_0_4 = new Wrapper_DoContactItem();
    this._appEl_0.initComponent(this._DoContactItem_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DoContactItem_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DoContactItem) && (0 === requestNodeIndex))) { return this._DoContactItem_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DoContactItem_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoContactItem_Host0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  if ((renderType_DoContactItem_Host === (null as any))) { (renderType_DoContactItem_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DoContactItem_Host0(viewUtils,parentInjector,declarationEl);
}
export const DoContactItemNgFactory:import9.ComponentFactory<import0.DoContactItem> = new import9.ComponentFactory<import0.DoContactItem>('do-contact-item',viewFactory_DoContactItem_Host0,import0.DoContactItem);
const styles_DoContactItem:any[] = ([] as any[]);
var renderType_DoContactItem:import4.RenderComponentType = (null as any);
class _View_DoContactItem0 extends import3.AppView<import0.DoContactItem> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _Item_0_4:import10.Wrapper_Item;
  _ItemContent_0_5:import10.Wrapper_ItemContent;
  _query_Label_0_0:import11.QueryList<any>;
  _query_Button_0_1:import11.QueryList<any>;
  _query_Icon_0_2:import11.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Avatar_2_3:import12.Wrapper_Avatar;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import5.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import13.Wrapper_NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import5.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import13.Wrapper_NgIf;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactItem0,renderType_DoContactItem,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'detail-none','');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import10.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import10.Wrapper_Item(this.parentInjector.get(import14.Form),this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import10.Wrapper_ItemContent();
    this._query_Label_0_0 = new import11.QueryList<any>();
    this._query_Button_0_1 = new import11.QueryList<any>();
    this._query_Icon_0_2 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this._Avatar_2_3 = new import12.Wrapper_Avatar();
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import5.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import17.TemplateRef_(this._appEl_4,viewFactory_DoContactItem1);
    this._NgIf_4_6 = new import13.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_6 = new import5.AppElement(6,2,this,this._anchor_6);
    this._TemplateRef_6_5 = new import17.TemplateRef_(this._appEl_6,viewFactory_DoContactItem2);
    this._NgIf_6_6 = new import13.Wrapper_NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_8
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_3 = import1.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import18.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import17.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import18.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6.context; }
    if (((token === import19.Avatar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Avatar_2_3.context; }
    if (((token === import20.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Item_0_4.context; }
    if (((token === import20.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Avatar_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_1:any = this.context.avatar;
    this._NgIf_4_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    const currVal_2:boolean = (!this.context.avatar || (0 === this.context.avatar.length));
    this._NgIf_6_6.check_ngIf(currVal_2,throwOnChange,false);
    this._NgIf_6_6.detectChangesInternal(this,this._anchor_6,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_3:any = import2.interpolate(1,'\n    ',this.context.name,'\n');
    if (import2.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_8,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onContactItemClick($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DoContactItem0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<import0.DoContactItem> {
  if ((renderType_DoContactItem === (null as any))) { (renderType_DoContactItem = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_DoContactItem,{})); }
  return new _View_DoContactItem0(viewUtils,parentInjector,declarationEl);
}
class _View_DoContactItem1 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactItem1,renderType_DoContactItem,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','fixed');
    this._expr_0 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.avatar;
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoContactItem1(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoContactItem1(viewUtils,parentInjector,declarationEl);
}
class _View_DoContactItem2 extends import3.AppView<any> {
  _el_0:any;
  _ColorGenerator_0_3:import22.ColorGenerator;
  _TextImage_0_4:import23.Wrapper_TextImage;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoContactItem2,renderType_DoContactItem,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'text-img',(null as any));
    this._ColorGenerator_0_3 = new import22.ColorGenerator();
    this._TextImage_0_4 = new import23.Wrapper_TextImage(new import16.ElementRef(this._el_0),this._ColorGenerator_0_3);
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.ColorGenerator) && (0 === requestNodeIndex))) { return this._ColorGenerator_0_3; }
    if (((token === import24.TextImage) && (0 === requestNodeIndex))) { return this._TextImage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.name;
    this._TextImage_0_4.check_text(currVal_0,throwOnChange,false);
    this._TextImage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoContactItem2(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoContactItem2(viewUtils,parentInjector,declarationEl);
}