/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './do-contact-list';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../providers/data-service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import16 from 'ionic-angular/config/config';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from 'ionic-angular/gestures/gesture-controller';
import * as import19 from 'ionic-angular/util/form';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import22 from 'ionic-angular/components/icon/icon';
import * as import23 from 'ionic-angular/components/item/item';
import * as import24 from '@angular/common/src/directives/ng_for';
import * as import25 from 'ionic-angular/components/list/list';
import * as import26 from './do-contact-item.ngfactory';
import * as import27 from './do-contact-item';
export class Wrapper_DoContactList {
  context:import0.DoContactList;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.DoContactList(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_DoContactList_Host:import2.RenderComponentType = (null as any);
class _View_DoContactList_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _DoContactList_0_4:Wrapper_DoContactList;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DoContactList_Host0,renderType_DoContactList_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('do-contact-list',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DoContactList0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoContactList_0_4 = new Wrapper_DoContactList(this.parentInjector.get(import8.DoDataService));
    this._appEl_0.initComponent(this._DoContactList_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DoContactList_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DoContactList) && (0 === requestNodeIndex))) { return this._DoContactList_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DoContactList_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoContactList_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_DoContactList_Host === (null as any))) { (renderType_DoContactList_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DoContactList_Host0(viewUtils,parentInjector,declarationEl);
}
export const DoContactListNgFactory:import10.ComponentFactory<import0.DoContactList> = new import10.ComponentFactory<import0.DoContactList>('do-contact-list',viewFactory_DoContactList_Host0,import0.DoContactList);
const styles_DoContactList:any[] = ([] as any[]);
var renderType_DoContactList:import2.RenderComponentType = (null as any);
class _View_DoContactList0 extends import1.AppView<import0.DoContactList> {
  _el_0:any;
  _List_0_3:import11.Wrapper_List;
  _text_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Item_4_4:import12.Wrapper_Item;
  _ItemContent_4_5:import12.Wrapper_ItemContent;
  _query_Label_4_0:import13.QueryList<any>;
  _query_Button_4_1:import13.QueryList<any>;
  _query_Icon_4_2:import13.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import14.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Item_9_4:import12.Wrapper_Item;
  _ItemContent_9_5:import12.Wrapper_ItemContent;
  _query_Label_9_0:import13.QueryList<any>;
  _query_Button_9_1:import13.QueryList<any>;
  _query_Icon_9_2:import13.QueryList<any>;
  _text_10:any;
  _el_11:any;
  _Icon_11_3:import14.Wrapper_Icon;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Item_14_4:import12.Wrapper_Item;
  _ItemContent_14_5:import12.Wrapper_ItemContent;
  _query_Label_14_0:import13.QueryList<any>;
  _query_Button_14_1:import13.QueryList<any>;
  _query_Icon_14_2:import13.QueryList<any>;
  _text_15:any;
  _el_16:any;
  _Icon_16_3:import14.Wrapper_Icon;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _Item_19_4:import12.Wrapper_Item;
  _ItemContent_19_5:import12.Wrapper_ItemContent;
  _query_Label_19_0:import13.QueryList<any>;
  _query_Button_19_1:import13.QueryList<any>;
  _query_Icon_19_2:import13.QueryList<any>;
  _text_20:any;
  _el_21:any;
  _Icon_21_3:import14.Wrapper_Icon;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Item_24_4:import12.Wrapper_Item;
  _query_Label_24_0:import13.QueryList<any>;
  _query_Button_24_1:import13.QueryList<any>;
  _query_Icon_24_2:import13.QueryList<any>;
  _text_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import15.Wrapper_NgFor;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _Item_29_4:import12.Wrapper_Item;
  _query_Label_29_0:import13.QueryList<any>;
  _query_Button_29_1:import13.QueryList<any>;
  _query_Icon_29_2:import13.QueryList<any>;
  _text_30:any;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _TemplateRef_32_5:any;
  _NgFor_32_6:import15.Wrapper_NgFor;
  _text_33:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DoContactList0,renderType_DoContactList,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-list',(null as any));
    this._List_0_3 = new import11.Wrapper_List(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import18.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item item-block');
    this.renderer.setElementAttribute(this._el_4,'detail-none','');
    this.renderer.setElementAttribute(this._el_4,'ion-item','');
    this._appEl_4 = new import3.AppElement(4,0,this,this._el_4);
    var compView_4:any = import12.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import12.Wrapper_Item(this.parentInjector.get(import19.Form),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_4),this.renderer);
    this._ItemContent_4_5 = new import12.Wrapper_ItemContent();
    this._query_Label_4_0 = new import13.QueryList<any>();
    this._query_Button_4_1 = new import13.QueryList<any>();
    this._query_Icon_4_2 = new import13.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'color','weixinOrange');
    this.renderer.setElementAttribute(this._el_6,'item-left','');
    this.renderer.setElementAttribute(this._el_6,'name','add');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import14.Wrapper_Icon(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n     新的朋友\n  ',(null as any));
    this._query_Label_4_0.reset(([] as any[]));
    this._Item_4_4.context.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4.context,[
      ([] as any[]).concat([this._el_6]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_5,
        this._text_7
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','item item-block');
    this.renderer.setElementAttribute(this._el_9,'detail-none','');
    this.renderer.setElementAttribute(this._el_9,'ion-item','');
    this._appEl_9 = new import3.AppElement(9,0,this,this._el_9);
    var compView_9:any = import12.viewFactory_Item0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Item_9_4 = new import12.Wrapper_Item(this.parentInjector.get(import19.Form),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_9),this.renderer);
    this._ItemContent_9_5 = new import12.Wrapper_ItemContent();
    this._query_Label_9_0 = new import13.QueryList<any>();
    this._query_Button_9_1 = new import13.QueryList<any>();
    this._query_Icon_9_2 = new import13.QueryList<any>();
    this._appEl_9.initComponent(this._Item_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'color','weixinGreen');
    this.renderer.setElementAttribute(this._el_11,'item-left','');
    this.renderer.setElementAttribute(this._el_11,'name','contacts');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import14.Wrapper_Icon(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText((null as any),'\n     群聊\n  ',(null as any));
    this._query_Label_9_0.reset(([] as any[]));
    this._Item_9_4.context.contentLabel = this._query_Label_9_0.first;
    compView_9.create(this._Item_9_4.context,[
      ([] as any[]).concat([this._el_11]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._text_12
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item item-block');
    this.renderer.setElementAttribute(this._el_14,'detail-none','');
    this.renderer.setElementAttribute(this._el_14,'ion-item','');
    this._appEl_14 = new import3.AppElement(14,0,this,this._el_14);
    var compView_14:any = import12.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import12.Wrapper_Item(this.parentInjector.get(import19.Form),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_14),this.renderer);
    this._ItemContent_14_5 = new import12.Wrapper_ItemContent();
    this._query_Label_14_0 = new import13.QueryList<any>();
    this._query_Button_14_1 = new import13.QueryList<any>();
    this._query_Icon_14_2 = new import13.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_16,'color','weixinBlue');
    this.renderer.setElementAttribute(this._el_16,'item-left','');
    this.renderer.setElementAttribute(this._el_16,'name','pricetag');
    this.renderer.setElementAttribute(this._el_16,'role','img');
    this._Icon_16_3 = new import14.Wrapper_Icon(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText((null as any),'\n     标签\n  ',(null as any));
    this._query_Label_14_0.reset(([] as any[]));
    this._Item_14_4.context.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4.context,[
      ([] as any[]).concat([this._el_16]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._text_17
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','item item-block');
    this.renderer.setElementAttribute(this._el_19,'detail-none','');
    this.renderer.setElementAttribute(this._el_19,'ion-item','');
    this.renderer.setElementAttribute(this._el_19,'no-lines','');
    this._appEl_19 = new import3.AppElement(19,0,this,this._el_19);
    var compView_19:any = import12.viewFactory_Item0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Item_19_4 = new import12.Wrapper_Item(this.parentInjector.get(import19.Form),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_19),this.renderer);
    this._ItemContent_19_5 = new import12.Wrapper_ItemContent();
    this._query_Label_19_0 = new import13.QueryList<any>();
    this._query_Button_19_1 = new import13.QueryList<any>();
    this._query_Icon_19_2 = new import13.QueryList<any>();
    this._appEl_19.initComponent(this._Item_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_21,'color','weixinBlue');
    this.renderer.setElementAttribute(this._el_21,'item-left','');
    this.renderer.setElementAttribute(this._el_21,'name','ribbon');
    this.renderer.setElementAttribute(this._el_21,'role','img');
    this._Icon_21_3 = new import14.Wrapper_Icon(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_21),this.renderer);
    this._text_22 = this.renderer.createText((null as any),'\n     公众号\n  ',(null as any));
    this._query_Label_19_0.reset(([] as any[]));
    this._Item_19_4.context.contentLabel = this._query_Label_19_0.first;
    compView_19.create(this._Item_19_4.context,[
      ([] as any[]).concat([this._el_21]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_20,
        this._text_22
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_0,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','lcdivider item');
    this._appEl_24 = new import3.AppElement(24,0,this,this._el_24);
    var compView_24:any = import12.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import12.Wrapper_Item(this.parentInjector.get(import19.Form),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_24),this.renderer);
    this._query_Label_24_0 = new import13.QueryList<any>();
    this._query_Button_24_1 = new import13.QueryList<any>();
    this._query_Icon_24_2 = new import13.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'星标好友',(null as any));
    this._query_Label_24_0.reset(([] as any[]));
    this._Item_24_4.context.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_25]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_27 = new import3.AppElement(27,0,this,this._anchor_27);
    this._TemplateRef_27_5 = new import20.TemplateRef_(this._appEl_27,viewFactory_DoContactList1);
    this._NgFor_27_6 = new import15.Wrapper_NgFor(this._appEl_27.vcRef,this._TemplateRef_27_5,this.parentInjector.get(import21.IterableDiffers),this.ref);
    this._text_28 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_0,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','lcdivider item');
    this._appEl_29 = new import3.AppElement(29,0,this,this._el_29);
    var compView_29:any = import12.viewFactory_Item0(this.viewUtils,this.injector(29),this._appEl_29);
    this._Item_29_4 = new import12.Wrapper_Item(this.parentInjector.get(import19.Form),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_29),this.renderer);
    this._query_Label_29_0 = new import13.QueryList<any>();
    this._query_Button_29_1 = new import13.QueryList<any>();
    this._query_Icon_29_2 = new import13.QueryList<any>();
    this._appEl_29.initComponent(this._Item_29_4.context,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'普通朋友',(null as any));
    this._query_Label_29_0.reset(([] as any[]));
    this._Item_29_4.context.contentLabel = this._query_Label_29_0.first;
    compView_29.create(this._Item_29_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_30]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_32 = new import3.AppElement(32,0,this,this._anchor_32);
    this._TemplateRef_32_5 = new import20.TemplateRef_(this._appEl_32,viewFactory_DoContactList2);
    this._NgFor_32_6 = new import15.Wrapper_NgFor(this._appEl_32.vcRef,this._TemplateRef_32_5,this.parentInjector.get(import21.IterableDiffers),this.ref);
    this._text_33 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._anchor_32,
      this._text_33
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import23.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Item_4_4.context; }
    if (((token === import23.ItemContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ItemContent_4_5.context; }
    if (((token === import22.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3.context; }
    if (((token === import23.Item) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Item_9_4.context; }
    if (((token === import23.ItemContent) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ItemContent_9_5.context; }
    if (((token === import22.Icon) && (16 === requestNodeIndex))) { return this._Icon_16_3.context; }
    if (((token === import23.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Item_14_4.context; }
    if (((token === import23.ItemContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ItemContent_14_5.context; }
    if (((token === import22.Icon) && (21 === requestNodeIndex))) { return this._Icon_21_3.context; }
    if (((token === import23.Item) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Item_19_4.context; }
    if (((token === import23.ItemContent) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemContent_19_5.context; }
    if (((token === import23.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Item_24_4.context; }
    if (((token === import20.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import24.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    if (((token === import23.Item) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Item_29_4.context; }
    if (((token === import20.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import24.NgFor) && (32 === requestNodeIndex))) { return this._NgFor_32_6.context; }
    if (((token === import25.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._List_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._List_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    this._ItemContent_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_1:any = 'weixinOrange';
    this._Icon_6_3.check_color(currVal_1,throwOnChange,false);
    const currVal_2:any = 'add';
    this._Icon_6_3.check_name(currVal_2,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._Item_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._ItemContent_9_5.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_5:any = 'weixinGreen';
    this._Icon_11_3.check_color(currVal_5,throwOnChange,false);
    const currVal_6:any = 'contacts';
    this._Icon_11_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Item_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._ItemContent_14_5.detectChangesInternal(this,this._el_14,throwOnChange);
    const currVal_9:any = 'weixinBlue';
    this._Icon_16_3.check_color(currVal_9,throwOnChange,false);
    const currVal_10:any = 'pricetag';
    this._Icon_16_3.check_name(currVal_10,throwOnChange,false);
    this._Icon_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    if (this._Item_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    this._ItemContent_19_5.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_13:any = 'weixinBlue';
    this._Icon_21_3.check_color(currVal_13,throwOnChange,false);
    const currVal_14:any = 'ribbon';
    this._Icon_21_3.check_name(currVal_14,throwOnChange,false);
    this._Icon_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    if (this._Item_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    const currVal_16:any = this.context.staredFriends;
    this._NgFor_27_6.check_ngForOf(currVal_16,throwOnChange,false);
    this._NgFor_27_6.detectChangesInternal(this,this._anchor_27,throwOnChange);
    if (this._Item_29_4.detectChangesInternal(this,this._el_29,throwOnChange)) { this._appEl_29.componentView.markAsCheckOnce(); }
    const currVal_17:any = this.context.friends;
    this._NgFor_32_6.check_ngForOf(currVal_17,throwOnChange,false);
    this._NgFor_32_6.detectChangesInternal(this,this._anchor_32,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset(([] as any[]));
        this._Item_4_4.context._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset([this._Icon_6_3.context]);
        this._Item_4_4.context._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if (this._query_Button_9_1.dirty) {
        this._query_Button_9_1.reset(([] as any[]));
        this._Item_9_4.context._buttons = this._query_Button_9_1;
        this._query_Button_9_1.notifyOnChanges();
      }
      if (this._query_Icon_9_2.dirty) {
        this._query_Icon_9_2.reset([this._Icon_11_3.context]);
        this._Item_9_4.context._icons = this._query_Icon_9_2;
        this._query_Icon_9_2.notifyOnChanges();
      }
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset(([] as any[]));
        this._Item_14_4.context._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset([this._Icon_16_3.context]);
        this._Item_14_4.context._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_19_1.dirty) {
        this._query_Button_19_1.reset(([] as any[]));
        this._Item_19_4.context._buttons = this._query_Button_19_1;
        this._query_Button_19_1.notifyOnChanges();
      }
      if (this._query_Icon_19_2.dirty) {
        this._query_Icon_19_2.reset([this._Icon_21_3.context]);
        this._Item_19_4.context._icons = this._query_Icon_19_2;
        this._query_Icon_19_2.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset(([] as any[]));
        this._Item_24_4.context._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset(([] as any[]));
        this._Item_24_4.context._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_29_1.dirty) {
        this._query_Button_29_1.reset(([] as any[]));
        this._Item_29_4.context._buttons = this._query_Button_29_1;
        this._query_Button_29_1.notifyOnChanges();
      }
      if (this._query_Icon_29_2.dirty) {
        this._query_Icon_29_2.reset(([] as any[]));
        this._Item_29_4.context._icons = this._query_Icon_29_2;
        this._query_Icon_29_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_9_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_14_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_19_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_24_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_29_4.context.ngAfterContentInit(); }
    }
    const currVal_3:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = this._Icon_11_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_11:any = this._Icon_16_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_16,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_15:any = this._Icon_21_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_21,'hide',currVal_15);
      this._expr_15 = currVal_15;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Icon_11_3.context.ngOnDestroy();
    this._Icon_16_3.context.ngOnDestroy();
    this._Icon_21_3.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.popupSearchFriend($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.popupGroupChat($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.popupEditTag($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.popupOfficialAccounts($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DoContactList0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.DoContactList> {
  if ((renderType_DoContactList === (null as any))) { (renderType_DoContactList = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_DoContactList,{})); }
  return new _View_DoContactList0(viewUtils,parentInjector,declarationEl);
}
class _View_DoContactList1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _DoContactItem_0_4:import26.Wrapper_DoContactItem;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DoContactList1,renderType_DoContactList,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'do-contact-item',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import26.viewFactory_DoContactItem0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoContactItem_0_4 = new import26.Wrapper_DoContactItem();
    this._appEl_0.initComponent(this._DoContactItem_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_0.create(this._DoContactItem_0_4.context,([] as any[]),(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'contactClicked',this.eventHandler(this._handle_contactClicked_0_0.bind(this)));
    const subscription_0:any = this._DoContactItem_0_4.context.contactClicked.subscribe(this.eventHandler(this._handle_contactClicked_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.DoContactItem) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._DoContactItem_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.$implicit.clientId;
    this._DoContactItem_0_4.check_friendId(currVal_1,throwOnChange,false);
    const currVal_2:any = this.context.$implicit.name;
    this._DoContactItem_0_4.check_friendName(currVal_2,throwOnChange,false);
    const currVal_3:any = this.context.$implicit.avatar;
    this._DoContactItem_0_4.check_avatarUrl(currVal_3,throwOnChange,false);
    this._DoContactItem_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_contactClicked_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onContactItemClick(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DoContactList1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_DoContactList1(viewUtils,parentInjector,declarationEl);
}
class _View_DoContactList2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _DoContactItem_0_4:import26.Wrapper_DoContactItem;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DoContactList2,renderType_DoContactList,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'do-contact-item',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import26.viewFactory_DoContactItem0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoContactItem_0_4 = new import26.Wrapper_DoContactItem();
    this._appEl_0.initComponent(this._DoContactItem_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_0.create(this._DoContactItem_0_4.context,([] as any[]),(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'contactClicked',this.eventHandler(this._handle_contactClicked_0_0.bind(this)));
    const subscription_0:any = this._DoContactItem_0_4.context.contactClicked.subscribe(this.eventHandler(this._handle_contactClicked_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.DoContactItem) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._DoContactItem_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.$implicit.clientId;
    this._DoContactItem_0_4.check_friendId(currVal_1,throwOnChange,false);
    const currVal_2:any = this.context.$implicit.name;
    this._DoContactItem_0_4.check_friendName(currVal_2,throwOnChange,false);
    const currVal_3:any = this.context.$implicit.avatar;
    this._DoContactItem_0_4.check_avatarUrl(currVal_3,throwOnChange,false);
    this._DoContactItem_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_contactClicked_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onContactItemClick(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DoContactList2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_DoContactList2(viewUtils,parentInjector,declarationEl);
}