/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import11 from '@angular/core/src/linker/component_factory';
export declare class Wrapper_LoginPage {
    context: import0.LoginPage;
    changed: boolean;
    constructor(p0: any, p1: any);
    detectChangesInternal(view: import1.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare const LoginPageNgFactory: import11.ComponentFactory<import0.LoginPage>;
export declare function viewFactory_LoginPage0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import3.AppElement): import1.AppView<import0.LoginPage>;
