/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/data-service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/toolbar/toolbar';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from 'ionic-angular/gestures/gesture-controller';
import * as import33 from 'ionic-angular/util/form';
import * as import34 from 'ionic-angular/platform/platform';
import * as import35 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import36 from 'ionic-angular/components/navbar/navbar';
import * as import37 from 'ionic-angular/components/label/label';
import * as import38 from '@angular/forms/src/directives/ng_model';
import * as import39 from '@angular/forms/src/directives/ng_control';
import * as import40 from '@angular/forms/src/directives/ng_control_status';
import * as import41 from 'ionic-angular/components/input/input';
import * as import42 from 'ionic-angular/components/item/item';
import * as import43 from 'ionic-angular/components/button/button';
import * as import44 from 'ionic-angular/components/list/list';
import * as import45 from 'ionic-angular/components/content/content';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginPage_0_4:Wrapper_LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new Wrapper_LoginPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.DoDataService));
    this._appEl_0.initComponent(this._LoginPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import11.ComponentFactory<import0.LoginPage> = new import11.ComponentFactory<import0.LoginPage>('page-login',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ([] as any[]);
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import14.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import15.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _List_11_3:import16.Wrapper_List;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _Item_13_4:import17.Wrapper_Item;
  _ItemContent_13_5:import17.Wrapper_ItemContent;
  _query_Label_13_0:import18.QueryList<any>;
  _query_Button_13_1:import18.QueryList<any>;
  _query_Icon_13_2:import18.QueryList<any>;
  _text_14:any;
  _el_15:any;
  _Label_15_3:import19.Wrapper_Label;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _NgModel_18_4:import20.Wrapper_NgModel;
  _NgControl_18_5:any;
  _NgControlStatus_18_6:import21.Wrapper_NgControlStatus;
  _TextInput_18_7:import22.Wrapper_TextInput;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _Button_21_4:import23.Wrapper_Button;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'login',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import15.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','reset');
    this._List_11_3 = new import16.Wrapper_List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import32.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','item item-block');
    this._appEl_13 = new import3.AppElement(13,11,this,this._el_13);
    var compView_13:any = import17.viewFactory_Item0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Item_13_4 = new import17.Wrapper_Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_13),this.renderer);
    this._ItemContent_13_5 = new import17.Wrapper_ItemContent();
    this._query_Label_13_0 = new import18.QueryList<any>();
    this._query_Button_13_1 = new import18.QueryList<any>();
    this._query_Icon_13_2 = new import18.QueryList<any>();
    this._appEl_13.initComponent(this._Item_13_4.context,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_15,'floating','');
    this._Label_15_3 = new import19.Wrapper_Label(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_15),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'输入一个 ClientId',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_18,'type','text');
    this._appEl_18 = new import3.AppElement(18,13,this,this._el_18);
    var compView_18:any = import22.viewFactory_TextInput0(this.viewUtils,this.injector(18),this._appEl_18);
    this._NgModel_18_4 = new import20.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_18_5 = this._NgModel_18_4.context;
    this._NgControlStatus_18_6 = new import21.Wrapper_NgControlStatus(this._NgControl_18_5);
    this._TextInput_18_7 = new import22.Wrapper_TextInput(this.parentInjector.get(import24.Config),this.parentInjector.get(import33.Form),this._Item_13_4.context,this.parentInjector.get(import27.App),this.parentInjector.get(import34.Platform),new import25.ElementRef(this._el_18),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_18_5);
    this._appEl_18.initComponent(this._TextInput_18_7.context,([] as any[]),compView_18);
    compView_18.create(this._TextInput_18_7.context,([] as any[]),(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_13_0.reset([this._Label_15_3.context]);
    this._Item_13_4.context.contentLabel = this._query_Label_13_0.first;
    compView_13.create(this._Item_13_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_15]),
      ([] as any[]).concat([
        this._text_14,
        this._text_17,
        this._text_19
      ]
      ),
      ([] as any[]).concat([this._el_18]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'block','');
    this.renderer.setElementAttribute(this._el_21,'ion-button','');
    this._appEl_21 = new import3.AppElement(21,11,this,this._el_21);
    var compView_21:any = import23.viewFactory_Button0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Button_21_4 = new import23.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_21),this.renderer);
    this._appEl_21.initComponent(this._Button_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'Go',(null as any));
    compView_21.create(this._Button_21_4.context,[([] as any[]).concat([this._text_22])],(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_24
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_18,'ngModelChange',this.eventHandler(this._handle_ngModelChange_18_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_18,'keypress',this.eventHandler(this._handle_keypress_18_1.bind(this)));
    const subscription_0:any = this._NgModel_18_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_18_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import35.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import36.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import28.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import37.Label) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Label_15_3.context; }
    if (((token === import38.NgModel) && (18 === requestNodeIndex))) { return this._NgModel_18_4.context; }
    if (((token === import39.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_5; }
    if (((token === import40.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_6.context; }
    if (((token === import41.TextInput) && (18 === requestNodeIndex))) { return this._TextInput_18_7.context; }
    if (((token === import42.Item) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_13_4.context; }
    if (((token === import42.ItemContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemContent_13_5.context; }
    if (((token === import43.Button) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Button_21_4.context; }
    if (((token === import44.List) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._List_11_3.context; }
    if (((token === import45.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._List_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Item_13_4.detectChangesInternal(this,this._el_13,throwOnChange)) { this._appEl_13.componentView.markAsCheckOnce(); }
    this._ItemContent_13_5.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Label_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_5:any = this.context.clientId;
    this._NgModel_18_4.check_model(currVal_5,throwOnChange,false);
    this._NgModel_18_4.detectChangesInternal(this,this._el_18,throwOnChange);
    this._NgControlStatus_18_6.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_12:any = 'text';
    this._TextInput_18_7.check_type(currVal_12,throwOnChange,false);
    this._TextInput_18_7.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_14:any = '';
    this._Button_21_4.check_block(currVal_14,throwOnChange,false);
    if (this._Button_21_4.detectChangesInternal(this,this._el_21,throwOnChange)) { this._appEl_21.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_13_1.dirty) {
        this._query_Button_13_1.reset(([] as any[]));
        this._Item_13_4.context._buttons = this._query_Button_13_1;
        this._query_Button_13_1.notifyOnChanges();
      }
      if (this._query_Icon_13_2.dirty) {
        this._query_Icon_13_2.reset(([] as any[]));
        this._Item_13_4.context._icons = this._query_Icon_13_2;
        this._query_Icon_13_2.notifyOnChanges();
      }
      this._TextInput_18_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_13_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_21_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._NgControlStatus_18_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_18_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_18_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_18_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_18_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_18_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_18_4.context.ngOnDestroy();
    this._TextInput_18_7.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.clientId = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_keypress_18_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onKeypress($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goHome($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}