/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './text-img';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
export class Wrapper_TextImage {
  context:import0.TextImage;
  changed:boolean;
  /*private*/ _text:any;
  /*private*/ _bgc:any;
  /*private*/ _badge:any;
  /*private*/ _img:any;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this._text = import1.UNINITIALIZED;
    this._bgc = import1.UNINITIALIZED;
    this._badge = import1.UNINITIALIZED;
    this._img = import1.UNINITIALIZED;
    this.context = new import0.TextImage(p0,p1);
  }
  check_text(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._text,currValue))) {
      this.changed = true;
      this.context.text = currValue;
      this._text = currValue;
    }
  }
  check_bgc(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._bgc,currValue))) {
      this.changed = true;
      this.context.bgc = currValue;
      this._bgc = currValue;
    }
  }
  check_badge(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._badge,currValue))) {
      this.changed = true;
      this.context.badge = currValue;
      this._badge = currValue;
    }
  }
  check_img(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._img,currValue))) {
      this.changed = true;
      this.context.img = currValue;
      this._img = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}