/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './text-img';
import * as import3 from '@angular/core/src/linker/view';
export declare class Wrapper_TextImage {
    context: import0.TextImage;
    changed: boolean;
    _text: any;
    _bgc: any;
    _badge: any;
    _img: any;
    constructor(p0: any, p1: any);
    check_text(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_bgc(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_badge(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_img(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
