/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './do-conversation-list';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import12 from '@angular/core/src/linker/component_factory';
export declare class Wrapper_DoConversationList {
    context: import0.DoConversationList;
    changed: boolean;
    _clientId: any;
    constructor(p0: any, p1: any, p2: any);
    check_clientId(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare const DoConversationListNgFactory: import12.ComponentFactory<import0.DoConversationList>;
export declare function viewFactory_DoConversationList0(viewUtils: import2.ViewUtils, parentInjector: import6.Injector, declarationEl: import5.AppElement): import3.AppView<import0.DoConversationList>;
