/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './do-conversation-item';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from 'ionic-angular/util/events';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import14 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import15 from 'ionic-angular/util/form';
import * as import16 from 'ionic-angular/config/config';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/common/src/directives/ng_if';
import * as import20 from 'ionic-angular/components/avatar/avatar';
import * as import21 from 'ionic-angular/components/item/item';
import * as import22 from '@angular/core/src/security';
import * as import23 from '../text-img/color-generator';
import * as import24 from '../text-img/text-img.ngfactory';
import * as import25 from '../text-img/text-img';
export class Wrapper_DoConversationItem {
  context:import0.DoConversationItem;
  changed:boolean;
  /*private*/ _convItem:any;
  constructor(p0:any) {
    this.changed = false;
    this._convItem = import1.UNINITIALIZED;
    this.context = new import0.DoConversationItem(p0);
  }
  check_convItem(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._convItem,currValue))) {
      this.changed = true;
      this.context.convItem = currValue;
      this._convItem = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_DoConversationItem_Host:import4.RenderComponentType = (null as any);
class _View_DoConversationItem_Host0 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _DoConversationItem_0_4:Wrapper_DoConversationItem;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoConversationItem_Host0,renderType_DoConversationItem_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('do-conversation-item',rootSelector,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DoConversationItem0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoConversationItem_0_4 = new Wrapper_DoConversationItem(this.parentInjector.get(import8.Events));
    this._appEl_0.initComponent(this._DoConversationItem_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DoConversationItem_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DoConversationItem) && (0 === requestNodeIndex))) { return this._DoConversationItem_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DoConversationItem_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoConversationItem_Host0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  if ((renderType_DoConversationItem_Host === (null as any))) { (renderType_DoConversationItem_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DoConversationItem_Host0(viewUtils,parentInjector,declarationEl);
}
export const DoConversationItemNgFactory:import10.ComponentFactory<import0.DoConversationItem> = new import10.ComponentFactory<import0.DoConversationItem>('do-conversation-item',viewFactory_DoConversationItem_Host0,import0.DoConversationItem);
const styles_DoConversationItem:any[] = ([] as any[]);
var renderType_DoConversationItem:import4.RenderComponentType = (null as any);
class _View_DoConversationItem0 extends import3.AppView<import0.DoConversationItem> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _Item_0_4:import11.Wrapper_Item;
  _ItemContent_0_5:import11.Wrapper_ItemContent;
  _query_Label_0_0:import12.QueryList<any>;
  _query_Button_0_1:import12.QueryList<any>;
  _query_Icon_0_2:import12.QueryList<any>;
  _text_1:any;
  _text_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _Avatar_5_3:import13.Wrapper_Avatar;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import5.AppElement;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import14.Wrapper_NgIf;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import5.AppElement;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import14.Wrapper_NgIf;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import5.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import14.Wrapper_NgIf;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import5.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import14.Wrapper_NgIf;
  _text_19:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoConversationItem0,renderType_DoConversationItem,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'detail-none','');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import11.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import11.Wrapper_Item(this.parentInjector.get(import15.Form),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import11.Wrapper_ItemContent();
    this._query_Label_0_0 = new import12.QueryList<any>();
    this._query_Button_0_1 = new import12.QueryList<any>();
    this._query_Icon_0_2 = new import12.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n   \n	',(null as any));
    this._text_2 = this.renderer.createText((null as any),'\n	',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n	',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_5,'item-left','');
    this._Avatar_5_3 = new import13.Wrapper_Avatar();
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_7 = new import5.AppElement(7,5,this,this._anchor_7);
    this._TemplateRef_7_5 = new import18.TemplateRef_(this._appEl_7,viewFactory_DoConversationItem1);
    this._NgIf_7_6 = new import14.Wrapper_NgIf(this._appEl_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_9 = new import5.AppElement(9,5,this,this._anchor_9);
    this._TemplateRef_9_5 = new import18.TemplateRef_(this._appEl_9,viewFactory_DoConversationItem2);
    this._NgIf_9_6 = new import14.Wrapper_NgIf(this._appEl_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_5,'\n	  ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_11 = new import5.AppElement(11,5,this,this._anchor_11);
    this._TemplateRef_11_5 = new import18.TemplateRef_(this._appEl_11,viewFactory_DoConversationItem3);
    this._NgIf_11_6 = new import14.Wrapper_NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_5,'\n     ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'p',(null as any));
    this._el_15 = this.renderer.createElement(this._el_14,'b',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n	',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_18 = new import5.AppElement(18,0,this,this._anchor_18);
    this._TemplateRef_18_5 = new import18.TemplateRef_(this._appEl_18,viewFactory_DoConversationItem4);
    this._NgIf_18_6 = new import14.Wrapper_NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText((null as any),'\n',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_2,
        this._text_3,
        this._text_4,
        this._text_13,
        this._el_14,
        this._text_17,
        this._appEl_18,
        this._text_19
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import1.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._anchor_18,
      this._text_19
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import19.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6.context; }
    if (((token === import18.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import19.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6.context; }
    if (((token === import18.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import19.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import20.Avatar) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Avatar_5_3.context; }
    if (((token === import18.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import19.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6.context; }
    if (((token === import21.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_0_4.context; }
    if (((token === import21.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Avatar_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_1:any = this.context.hasImage;
    this._NgIf_7_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_7_6.detectChangesInternal(this,this._anchor_7,throwOnChange);
    const currVal_2:boolean = !this.context.hasImage;
    this._NgIf_9_6.check_ngIf(currVal_2,throwOnChange,false);
    this._NgIf_9_6.detectChangesInternal(this,this._anchor_9,throwOnChange);
    const currVal_3:any = (this.context.conv.unreadBadge > 0);
    this._NgIf_11_6.check_ngIf(currVal_3,throwOnChange,false);
    this._NgIf_11_6.detectChangesInternal(this,this._anchor_11,throwOnChange);
    const currVal_5:any = this.context.hasLastMessage;
    this._NgIf_18_6.check_ngIf(currVal_5,throwOnChange,false);
    this._NgIf_18_6.detectChangesInternal(this,this._anchor_18,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = import2.interpolate(1,'',this.context.conv.name,'');
    if (import2.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_16,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onConversationItemClick(this.context.conv)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DoConversationItem0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<import0.DoConversationItem> {
  if ((renderType_DoConversationItem === (null as any))) { (renderType_DoConversationItem = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_DoConversationItem,{})); }
  return new _View_DoConversationItem0(viewUtils,parentInjector,declarationEl);
}
class _View_DoConversationItem1 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoConversationItem1,renderType_DoConversationItem,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','fixed');
    this._expr_0 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.conv.titleImg;
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import22.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoConversationItem1(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoConversationItem1(viewUtils,parentInjector,declarationEl);
}
class _View_DoConversationItem2 extends import3.AppView<any> {
  _el_0:any;
  _ColorGenerator_0_3:import23.ColorGenerator;
  _TextImage_0_4:import24.Wrapper_TextImage;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoConversationItem2,renderType_DoConversationItem,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'text-img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'item-left','');
    this._ColorGenerator_0_3 = new import23.ColorGenerator();
    this._TextImage_0_4 = new import24.Wrapper_TextImage(new import17.ElementRef(this._el_0),this._ColorGenerator_0_3);
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.ColorGenerator) && (0 === requestNodeIndex))) { return this._ColorGenerator_0_3; }
    if (((token === import25.TextImage) && (0 === requestNodeIndex))) { return this._TextImage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.conv.name;
    this._TextImage_0_4.check_text(currVal_0,throwOnChange,false);
    this._TextImage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoConversationItem2(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoConversationItem2(viewUtils,parentInjector,declarationEl);
}
class _View_DoConversationItem3 extends import3.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoConversationItem3,renderType_DoConversationItem,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','conv-badge');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import2.interpolate(1,'',this.parent.context.conv.unreadBadge,'');
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoConversationItem3(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoConversationItem3(viewUtils,parentInjector,declarationEl);
}
class _View_DoConversationItem4 extends import3.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoConversationItem4,renderType_DoConversationItem,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'b',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import2.interpolate(1,'',this.parent.context.conv.lastMessage.from,'');
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_2,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import2.interpolate(1,': ',this.parent.context.conv.lastMessage.text,'');
    if (import2.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoConversationItem4(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoConversationItem4(viewUtils,parentInjector,declarationEl);
}