/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './lc-contact-list';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from 'ionic-angular/components/list/list';
import * as import11 from 'ionic-angular/components/item/item';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from 'ionic-angular/components/icon/icon';
import * as import14 from 'ionic-angular/config/config';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from 'ionic-angular/gestures/gesture-controller';
import * as import17 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import18 from 'ionic-angular/util/form';
var renderType_LCContactList_Host:import0.RenderComponentType = (null as any);
class _View_LCContactList_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LCContactList_0_4:import3.LCContactList;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LCContactList_Host0,renderType_LCContactList_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('lc-contact-list',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LCContactList0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LCContactList_0_4 = new import3.LCContactList();
    this._appEl_0.initComponent(this._LCContactList_0_4,([] as any[]),compView_0);
    compView_0.create(this._LCContactList_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LCContactList) && (0 === requestNodeIndex))) { return this._LCContactList_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LCContactList_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LCContactList_Host === (null as any))) { (renderType_LCContactList_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LCContactList_Host0(viewUtils,parentInjector,declarationEl);
}
export const LCContactListNgFactory:import9.ComponentFactory<import3.LCContactList> = new import9.ComponentFactory<import3.LCContactList>('lc-contact-list',viewFactory_LCContactList_Host0,import3.LCContactList);
const styles_LCContactList:any[] = ([] as any[]);
var renderType_LCContactList:import0.RenderComponentType = (null as any);
class _View_LCContactList0 extends import1.AppView<import3.LCContactList> {
  _el_0:any;
  _List_0_3:import10.List;
  _text_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Item_4_4:import11.Item;
  _ItemContent_4_5:import11.ItemContent;
  _query_Label_4_0:import12.QueryList<any>;
  _query_Button_4_1:import12.QueryList<any>;
  _query_Icon_4_2:import12.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import13.Icon;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Item_12_4:import11.Item;
  _ItemContent_12_5:import11.ItemContent;
  _query_Label_12_0:import12.QueryList<any>;
  _query_Button_12_1:import12.QueryList<any>;
  _query_Icon_12_2:import12.QueryList<any>;
  _text_13:any;
  _el_14:any;
  _Icon_14_3:import13.Icon;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Item_20_4:import11.Item;
  _ItemContent_20_5:import11.ItemContent;
  _query_Label_20_0:import12.QueryList<any>;
  _query_Button_20_1:import12.QueryList<any>;
  _query_Icon_20_2:import12.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Icon_22_3:import13.Icon;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _Item_28_4:import11.Item;
  _ItemContent_28_5:import11.ItemContent;
  _query_Label_28_0:import12.QueryList<any>;
  _query_Button_28_1:import12.QueryList<any>;
  _query_Icon_28_2:import12.QueryList<any>;
  _text_29:any;
  _el_30:any;
  _Icon_30_3:import13.Icon;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LCContactList0,renderType_LCContactList,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-list',(null as any));
    this._List_0_3 = new import10.List(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import16.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item item-block');
    this.renderer.setElementAttribute(this._el_4,'detail-none','');
    this.renderer.setElementAttribute(this._el_4,'ion-item','');
    this._appEl_4 = new import2.AppElement(4,0,this,this._el_4);
    var compView_4:any = import17.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import11.Item(this.parentInjector.get(import18.Form),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_4),this.renderer);
    this._ItemContent_4_5 = new import11.ItemContent();
    this._query_Label_4_0 = new import12.QueryList<any>();
    this._query_Button_4_1 = new import12.QueryList<any>();
    this._query_Icon_4_2 = new import12.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'item-left','');
    this.renderer.setElementAttribute(this._el_6,'name','add');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import13.Icon(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'b',(null as any));
    this.renderer.setElementAttribute(this._el_8,'item-left','');
    this._text_9 = this.renderer.createText(this._el_8,'新的朋友',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_4_0.reset(([] as any[]));
    this._Item_4_4.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4,[
      ([] as any[]).concat([
        this._el_6,
        this._el_8
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_5,
        this._text_7,
        this._text_10
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','item item-block');
    this.renderer.setElementAttribute(this._el_12,'detail-none','');
    this.renderer.setElementAttribute(this._el_12,'ion-item','');
    this._appEl_12 = new import2.AppElement(12,0,this,this._el_12);
    var compView_12:any = import17.viewFactory_Item0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Item_12_4 = new import11.Item(this.parentInjector.get(import18.Form),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_12),this.renderer);
    this._ItemContent_12_5 = new import11.ItemContent();
    this._query_Label_12_0 = new import12.QueryList<any>();
    this._query_Button_12_1 = new import12.QueryList<any>();
    this._query_Icon_12_2 = new import12.QueryList<any>();
    this._appEl_12.initComponent(this._Item_12_4,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_14,'item-left','');
    this.renderer.setElementAttribute(this._el_14,'name','contacts');
    this.renderer.setElementAttribute(this._el_14,'role','img');
    this._Icon_14_3 = new import13.Icon(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'b',(null as any));
    this.renderer.setElementAttribute(this._el_16,'item-left','');
    this._text_17 = this.renderer.createText(this._el_16,'群聊',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_12_0.reset(([] as any[]));
    this._Item_12_4.contentLabel = this._query_Label_12_0.first;
    compView_12.create(this._Item_12_4,[
      ([] as any[]).concat([
        this._el_14,
        this._el_16
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_13,
        this._text_15,
        this._text_18
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','item item-block');
    this.renderer.setElementAttribute(this._el_20,'detail-none','');
    this.renderer.setElementAttribute(this._el_20,'ion-item','');
    this._appEl_20 = new import2.AppElement(20,0,this,this._el_20);
    var compView_20:any = import17.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import11.Item(this.parentInjector.get(import18.Form),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_20),this.renderer);
    this._ItemContent_20_5 = new import11.ItemContent();
    this._query_Label_20_0 = new import12.QueryList<any>();
    this._query_Button_20_1 = new import12.QueryList<any>();
    this._query_Icon_20_2 = new import12.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_22,'item-left','');
    this.renderer.setElementAttribute(this._el_22,'name','pricetag');
    this.renderer.setElementAttribute(this._el_22,'role','img');
    this._Icon_22_3 = new import13.Icon(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'b',(null as any));
    this.renderer.setElementAttribute(this._el_24,'item-left','');
    this._text_25 = this.renderer.createText(this._el_24,'标签',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_20_0.reset(([] as any[]));
    this._Item_20_4.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4,[
      ([] as any[]).concat([
        this._el_22,
        this._el_24
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_21,
        this._text_23,
        this._text_26
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','item item-block');
    this.renderer.setElementAttribute(this._el_28,'detail-none','');
    this.renderer.setElementAttribute(this._el_28,'ion-item','');
    this._appEl_28 = new import2.AppElement(28,0,this,this._el_28);
    var compView_28:any = import17.viewFactory_Item0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Item_28_4 = new import11.Item(this.parentInjector.get(import18.Form),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_28),this.renderer);
    this._ItemContent_28_5 = new import11.ItemContent();
    this._query_Label_28_0 = new import12.QueryList<any>();
    this._query_Button_28_1 = new import12.QueryList<any>();
    this._query_Icon_28_2 = new import12.QueryList<any>();
    this._appEl_28.initComponent(this._Item_28_4,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_30,'item-left','');
    this.renderer.setElementAttribute(this._el_30,'name','ribbon');
    this.renderer.setElementAttribute(this._el_30,'role','img');
    this._Icon_30_3 = new import13.Icon(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'b',(null as any));
    this.renderer.setElementAttribute(this._el_32,'item-left','');
    this._text_33 = this.renderer.createText(this._el_32,'公众号',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_28_0.reset(([] as any[]));
    this._Item_28_4.contentLabel = this._query_Label_28_0.first;
    compView_28.create(this._Item_28_4,[
      ([] as any[]).concat([
        this._el_30,
        this._el_32
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_29,
        this._text_31,
        this._text_34
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import11.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Item_4_4; }
    if (((token === import11.ItemContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ItemContent_4_5; }
    if (((token === import13.Icon) && (14 === requestNodeIndex))) { return this._Icon_14_3; }
    if (((token === import11.Item) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Item_12_4; }
    if (((token === import11.ItemContent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ItemContent_12_5; }
    if (((token === import13.Icon) && (22 === requestNodeIndex))) { return this._Icon_22_3; }
    if (((token === import11.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_20_4; }
    if (((token === import11.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_20_5; }
    if (((token === import13.Icon) && (30 === requestNodeIndex))) { return this._Icon_30_3; }
    if (((token === import11.Item) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_28_4; }
    if (((token === import11.ItemContent) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_28_5; }
    if (((token === import10.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._List_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'add';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_6_3.name = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = 'contacts';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_14_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = 'pricetag';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_22_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = 'ribbon';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_30_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset(([] as any[]));
        this._Item_4_4._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset([this._Icon_6_3]);
        this._Item_4_4._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if (this._query_Button_12_1.dirty) {
        this._query_Button_12_1.reset(([] as any[]));
        this._Item_12_4._buttons = this._query_Button_12_1;
        this._query_Button_12_1.notifyOnChanges();
      }
      if (this._query_Icon_12_2.dirty) {
        this._query_Icon_12_2.reset([this._Icon_14_3]);
        this._Item_12_4._icons = this._query_Icon_12_2;
        this._query_Icon_12_2.notifyOnChanges();
      }
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset(([] as any[]));
        this._Item_20_4._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset([this._Icon_22_3]);
        this._Item_20_4._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if (this._query_Button_28_1.dirty) {
        this._query_Button_28_1.reset(([] as any[]));
        this._Item_28_4._buttons = this._query_Button_28_1;
        this._query_Button_28_1.notifyOnChanges();
      }
      if (this._query_Icon_28_2.dirty) {
        this._query_Icon_28_2.reset([this._Icon_30_3]);
        this._Item_28_4._icons = this._query_Icon_28_2;
        this._query_Icon_28_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_12_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_20_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_28_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._Icon_14_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_14,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._Icon_22_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_22,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._Icon_30_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_30,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Icon_14_3.ngOnDestroy();
    this._Icon_22_3.ngOnDestroy();
    this._Icon_30_3.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.popupSearchFriend($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.popupSearchFriend) !== false);
    return (true && pd_0);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.popupSearchFriend) !== false);
    return (true && pd_0);
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.popupSearchFriend) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LCContactList0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LCContactList> {
  if ((renderType_LCContactList === (null as any))) { (renderType_LCContactList = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_LCContactList,{})); }
  return new _View_LCContactList0(viewUtils,parentInjector,declarationEl);
}