import { EventEmitter, ChangeDetectorRef, OnInit, AfterViewInit, AfterContentInit } from '@angular/core';
import { Conversation } from 'leancloud-realtime';
import { Events, ViewController, NavController, Content, Refresher } from 'ionic-angular';
import { NgZone } from '@angular/core';
import { DoChatService, DoMessage, DoOperationMessage } from '../../providers/chat-service';
import { DoDataService } from '../../providers/data-service';
import { DoUserService, DoFriend } from '../../providers/user-service';
export declare class DoChat implements OnInit, AfterViewInit, AfterContentInit {
    events: Events;
    dataService: DoDataService;
    private ref;
    chatService: DoChatService;
    userService: DoUserService;
    viewCtrl: ViewController;
    navCtrl: NavController;
    chatContent: Content;
    refresher: Refresher;
    conversationId: string;
    conversationName: string;
    isPrivate: boolean;
    hasAvatar: boolean;
    convTitleImg: string;
    convTitleText: string;
    msgSum: string;
    loadingText: string;
    pullingText: string;
    noMoreRecord: boolean;
    randomLoadingText(): string;
    friendIds: string[];
    membersInConv: DoFriend[];
    orgeMessages: DoMessage[];
    opMessages: DoOperationMessage[];
    convId: string;
    convName: string;
    zone: NgZone;
    conv: Conversation;
    onMsg: EventEmitter<any>;
    scrollScreen(): void;
    constructor(events: Events, dataService: DoDataService, ref: ChangeDetectorRef, chatService: DoChatService, userService: DoUserService, viewCtrl: ViewController, navCtrl: NavController);
    ngOnInit(): void;
    initConv(): Promise<Conversation>;
    doRefresh(refresher: any): void;
    doStart(refresher: any): void;
    doPulling(refresher: Refresher): void;
    ngAfterViewInit(): void;
    ngAfterContentInit(): void;
    willLeave(): void;
}
