/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './do-chat';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from 'ionic-angular/util/events';
import * as import9 from '../../providers/data-service';
import * as import10 from '../../providers/chat-service';
import * as import11 from '../../providers/user-service';
import * as import12 from 'ionic-angular/navigation/view-controller';
import * as import13 from 'ionic-angular/navigation/nav-controller';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import18 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/refresher/refresher.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import24 from '../do-input-box/do-input-box.ngfactory';
import * as import25 from '../util-string-equal-pipe/util-string-equal-pipe';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from '@angular/core/src/linker/template_ref';
import * as import33 from 'ionic-angular/gestures/gesture-controller';
import * as import34 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import35 from '@angular/common/src/directives/ng_if';
import * as import36 from 'ionic-angular/components/refresher/refresher-content';
import * as import37 from 'ionic-angular/components/refresher/refresher';
import * as import38 from '@angular/common/src/directives/ng_for';
import * as import39 from 'ionic-angular/components/list/list';
import * as import40 from 'ionic-angular/components/content/content';
import * as import41 from '../do-input-box/do-input-box';
import * as import42 from 'ionic-angular/components/toolbar/toolbar';
import * as import43 from '@angular/core/src/security';
import * as import44 from '../text-img/color-generator';
import * as import45 from '../text-img/text-img.ngfactory';
import * as import46 from '../text-img/text-img';
import * as import47 from '../message-item/message-item.ngfactory';
import * as import48 from '../message-item/message-item';
export class Wrapper_DoChat {
  context:import0.DoChat;
  changed:boolean;
  /*private*/ _friendIds:any;
  /*private*/ _convId:any;
  /*private*/ _convName:any;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this.changed = false;
    this._friendIds = import1.UNINITIALIZED;
    this._convId = import1.UNINITIALIZED;
    this._convName = import1.UNINITIALIZED;
    this.context = new import0.DoChat(p0,p1,p2,p3,p4,p5,p6);
  }
  check_friendIds(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._friendIds,currValue))) {
      this.changed = true;
      this.context.friendIds = currValue;
      this._friendIds = currValue;
    }
  }
  check_convId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._convId,currValue))) {
      this.changed = true;
      this.context.convId = currValue;
      this._convId = currValue;
    }
  }
  check_convName(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._convName,currValue))) {
      this.changed = true;
      this.context.convName = currValue;
      this._convName = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_DoChat_Host:import4.RenderComponentType = (null as any);
class _View_DoChat_Host0 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _DoChat_0_4:Wrapper_DoChat;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoChat_Host0,renderType_DoChat_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('do-chat',rootSelector,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DoChat0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoChat_0_4 = new Wrapper_DoChat(this.parentInjector.get(import8.Events),this.parentInjector.get(import9.DoDataService),compView_0.ref,this.parentInjector.get(import10.DoChatService),this.parentInjector.get(import11.DoUserService),this.parentInjector.get(import12.ViewController),this.parentInjector.get(import13.NavController));
    this._appEl_0.initComponent(this._DoChat_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DoChat_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DoChat) && (0 === requestNodeIndex))) { return this._DoChat_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DoChat_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._DoChat_0_4.context.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._DoChat_0_4.context.ngAfterViewInit(); } }
  }
}
function viewFactory_DoChat_Host0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  if ((renderType_DoChat_Host === (null as any))) { (renderType_DoChat_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DoChat_Host0(viewUtils,parentInjector,declarationEl);
}
export const DoChatNgFactory:import15.ComponentFactory<import0.DoChat> = new import15.ComponentFactory<import0.DoChat>('do-chat',viewFactory_DoChat_Host0,import0.DoChat);
const styles_DoChat:any[] = ([] as any[]);
var renderType_DoChat:import4.RenderComponentType = (null as any);
class _View_DoChat0 extends import3.AppView<import0.DoChat> {
  _viewQuery_Content_0:import16.QueryList<any>;
  _viewQuery_Refresher_1:import16.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _Content_0_4:import17.Wrapper_Content;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import5.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import18.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import5.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import18.Wrapper_NgIf;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _List_23_3:import19.Wrapper_List;
  _text_24:any;
  _el_25:any;
  _Refresher_25_3:import20.Wrapper_Refresher;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import5.AppElement;
  _RefresherContent_27_4:import21.Wrapper_RefresherContent;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import5.AppElement;
  _TemplateRef_33_5:any;
  _NgFor_33_6:import22.Wrapper_NgFor;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import5.AppElement;
  _TemplateRef_35_5:any;
  _NgFor_35_6:import22.Wrapper_NgFor;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _Footer_39_3:import23.Wrapper_Footer;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import5.AppElement;
  _Toolbar_41_4:import23.Wrapper_Toolbar;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import5.AppElement;
  _DoInputBox_43_4:import24.Wrapper_DoInputBox;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_14:any;
  _pipe_strEquals_0:import25.StrEqualsPipe;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoChat0,renderType_DoChat,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Content_0 = new import16.QueryList<any>();
    this._viewQuery_Refresher_1 = new import16.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','do-chat');
    this.renderer.setElementAttribute(this._el_0,'id','chatContent');
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import17.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import17.Wrapper_Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import12.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','chat-header clearfix');
    this.renderer.setElementAttribute(this._el_2,'ion-fixed','');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import5.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import32.TemplateRef_(this._appEl_4,viewFactory_DoChat1);
    this._NgIf_4_6 = new import18.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'style','display: inline;float:left;');
    this._text_7 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_8 = new import5.AppElement(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import32.TemplateRef_(this._appEl_8,viewFactory_DoChat2);
    this._NgIf_8_6 = new import18.Wrapper_NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_6,'\n		',(null as any));
    this._text_10 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_11 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','chat-about');
    this._text_12 = this.renderer.createText(this._el_11,'\n			',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','chat-with');
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n			',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','chat-num-messages');
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n		',(null as any));
    this._text_19 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_20 = this.renderer.createElement(this._el_2,'i',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','fa fa-star');
    this._text_21 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','do-chat');
    this.renderer.setElementAttribute(this._el_23,'no-lines','');
    this._List_23_3 = new import19.Wrapper_List(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import33.GestureController));
    this._text_24 = this.renderer.createText(this._el_23,'\n		',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'ion-refresher',(null as any));
    this._Refresher_25_3 = new import20.Wrapper_Refresher(this._Content_0_4.context,this.parentInjector.get(import30.NgZone),this.parentInjector.get(import33.GestureController));
    this._text_26 = this.renderer.createText(this._el_25,'\n			',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'ion-refresher-content',(null as any));
    this.renderer.setElementAttribute(this._el_27,'pullingIcon','arrow-dropdown');
    this.renderer.setElementAttribute(this._el_27,'refreshingSpinner','circles');
    this._appEl_27 = new import5.AppElement(27,25,this,this._el_27);
    var compView_27:any = import21.viewFactory_RefresherContent0(this.viewUtils,this.injector(27),this._appEl_27);
    this._RefresherContent_27_4 = new import21.Wrapper_RefresherContent(this._Refresher_25_3.context,this.parentInjector.get(import26.Config));
    this._appEl_27.initComponent(this._RefresherContent_27_4.context,([] as any[]),compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n			',(null as any));
    compView_27.create(this._RefresherContent_27_4.context,([] as any[]),(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n		',(null as any));
    this._text_30 = this.renderer.createText(this._el_23,'\n		',(null as any));
    this._text_31 = this.renderer.createText(this._el_23,'\n		',(null as any));
    this._text_32 = this.renderer.createText(this._el_23,'\n		',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_33 = new import5.AppElement(33,23,this,this._anchor_33);
    this._TemplateRef_33_5 = new import32.TemplateRef_(this._appEl_33,viewFactory_DoChat3);
    this._NgFor_33_6 = new import22.Wrapper_NgFor(this._appEl_33.vcRef,this._TemplateRef_33_5,this.parentInjector.get(import34.IterableDiffers),this.ref);
    this._text_34 = this.renderer.createText(this._el_23,'\n\n\n		',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_35 = new import5.AppElement(35,23,this,this._anchor_35);
    this._TemplateRef_35_5 = new import32.TemplateRef_(this._appEl_35,viewFactory_DoChat4);
    this._NgFor_35_6 = new import22.Wrapper_NgFor(this._appEl_35.vcRef,this._TemplateRef_35_5,this.parentInjector.get(import34.IterableDiffers),this.ref);
    this._text_36 = this.renderer.createText(this._el_23,'\n	',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Content_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([
        this._text_1,
        this._text_22,
        this._el_23,
        this._text_37
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_38 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_39 = this.renderer.createElement(parentRenderNode,'ion-footer',(null as any));
    this._Footer_39_3 = new import23.Wrapper_Footer(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_39),this.renderer,this.parentInjector.get(import12.ViewController,(null as any)));
    this._text_40 = this.renderer.createText(this._el_39,'\n	',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','toolbar');
    this._appEl_41 = new import5.AppElement(41,39,this,this._el_41);
    var compView_41:any = import23.viewFactory_Toolbar0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Toolbar_41_4 = new import23.Wrapper_Toolbar(this.parentInjector.get(import12.ViewController,(null as any)),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_41),this.renderer);
    this._appEl_41.initComponent(this._Toolbar_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'do-input-box',(null as any));
    this._appEl_43 = new import5.AppElement(43,41,this,this._el_43);
    var compView_43:any = import24.viewFactory_DoInputBox0(this.viewUtils,this.injector(43),this._appEl_43);
    this._DoInputBox_43_4 = new import24.Wrapper_DoInputBox(this.parentInjector.get(import8.Events),this.parentInjector.get(import10.DoChatService),this.parentInjector.get(import12.ViewController));
    this._appEl_43.initComponent(this._DoInputBox_43_4.context,([] as any[]),compView_43);
    compView_43.create(this._DoInputBox_43_4.context,([] as any[]),(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_41.create(this._Toolbar_41_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_42,
        this._el_43,
        this._text_44
      ]
      )
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(this._el_39,'\n',(null as any));
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_25,'ionRefresh',this.eventHandler(this._handle_ionRefresh_25_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_25,'ionStart',this.eventHandler(this._handle_ionStart_25_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_25,'ionPull',this.eventHandler(this._handle_ionPull_25_2.bind(this)));
    this._expr_8 = import1.UNINITIALIZED;
    this._expr_9 = import1.UNINITIALIZED;
    const subscription_0:any = this._Refresher_25_3.context.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_25_0.bind(this)));
    const subscription_1:any = this._Refresher_25_3.context.ionPull.subscribe(this.eventHandler(this._handle_ionPull_25_2.bind(this)));
    const subscription_2:any = this._Refresher_25_3.context.ionStart.subscribe(this.eventHandler(this._handle_ionStart_25_1.bind(this)));
    this._expr_14 = import1.UNINITIALIZED;
    this._pipe_strEquals_0 = new import25.StrEqualsPipe();
    this._expr_17 = import1.UNINITIALIZED;
    this._viewQuery_Content_0.reset([this._Content_0_4.context]);
    this.context.chatContent = this._viewQuery_Content_0.first;
    this._viewQuery_Refresher_1.reset([this._Refresher_25_3.context]);
    this.context.refresher = this._viewQuery_Refresher_1.first;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import35.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import32.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import35.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6.context; }
    if (((token === import36.RefresherContent) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._RefresherContent_27_4.context; }
    if (((token === import37.Refresher) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Refresher_25_3.context; }
    if (((token === import32.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import38.NgFor) && (33 === requestNodeIndex))) { return this._NgFor_33_6.context; }
    if (((token === import32.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import38.NgFor) && (35 === requestNodeIndex))) { return this._NgFor_35_6.context; }
    if (((token === import39.List) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._List_23_3.context; }
    if (((token === import40.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Content_0_4.context; }
    if (((token === import41.DoInputBox) && (43 === requestNodeIndex))) { return this._DoInputBox_43_4.context; }
    if (((token === import42.Toolbar) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Toolbar_41_4.context; }
    if (((token === import42.Footer) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Footer_39_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_1:any = this.context.hasAvatar;
    this._NgIf_4_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    const currVal_2:boolean = !this.context.hasAvatar;
    this._NgIf_8_6.check_ngIf(currVal_2,throwOnChange,false);
    this._NgIf_8_6.detectChangesInternal(this,this._anchor_8,throwOnChange);
    this._List_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Refresher_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_10:any = 'arrow-dropdown';
    this._RefresherContent_27_4.check_pullingIcon(currVal_10,throwOnChange,false);
    const currVal_11:any = this.context.pullingText;
    this._RefresherContent_27_4.check_pullingText(currVal_11,throwOnChange,false);
    const currVal_12:any = 'circles';
    this._RefresherContent_27_4.check_refreshingSpinner(currVal_12,throwOnChange,false);
    const currVal_13:any = this.context.loadingText;
    this._RefresherContent_27_4.check_refreshingText(currVal_13,throwOnChange,false);
    this._RefresherContent_27_4.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_15:any = this.context.orgeMessages;
    this._NgFor_33_6.check_ngForOf(currVal_15,throwOnChange,false);
    this._NgFor_33_6.detectChangesInternal(this,this._anchor_33,throwOnChange);
    const currVal_16:any = this.context.opMessages;
    this._NgFor_35_6.check_ngForOf(currVal_16,throwOnChange,false);
    this._NgFor_35_6.detectChangesInternal(this,this._anchor_35,throwOnChange);
    this._Footer_39_3.detectChangesInternal(this,this._el_39,throwOnChange);
    if (this._Toolbar_41_4.detectChangesInternal(this,this._el_41,throwOnChange)) { this._appEl_41.componentView.markAsCheckOnce(); }
    const currVal_18:any = this.context.conv;
    this._DoInputBox_43_4.check_conv(currVal_18,throwOnChange,false);
    this._DoInputBox_43_4.detectChangesInternal(this,this._el_43,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Content_0_4.context._sbPadding;
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = import2.interpolate(1,'',this.context.convTitleText,'');
    if (import2.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_14,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import2.interpolate(1,'',this.context.msgSum,'');
    if (import2.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_17,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_8:any = (this._Refresher_25_3.context.state !== 'inactive');
    if (import2.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_25,'refresher-active',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._Refresher_25_3.context._top;
    if (import2.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementStyle(this._el_25,'top',((this.viewUtils.sanitizer.sanitize(import43.SecurityContext.STYLE,currVal_9) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import43.SecurityContext.STYLE,currVal_9).toString()));
      this._expr_9 = currVal_9;
    }
    const currVal_14:any = this._RefresherContent_27_4.context.r.state;
    if (import2.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementAttribute(this._el_27,'state',((currVal_14 == (null as any))? (null as any): currVal_14.toString()));
      this._expr_14 = currVal_14;
    }
    const currVal_17:any = this._Toolbar_41_4.context._sbPadding;
    if (import2.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_41,'statusbar-padding',currVal_17);
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Refresher_25_3.context.ngOnDestroy();
    this._Content_0_4.context.ngOnDestroy();
  }
  private _handle_ionRefresh_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRefresh($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionStart_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doStart($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionPull_25_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doPulling($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DoChat0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<import0.DoChat> {
  if ((renderType_DoChat === (null as any))) { (renderType_DoChat = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_DoChat,{})); }
  return new _View_DoChat0(viewUtils,parentInjector,declarationEl);
}
class _View_DoChat1 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoChat1,renderType_DoChat,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','fixed doAvatar');
    this._expr_0 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.convTitleImg;
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import43.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoChat1(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoChat1(viewUtils,parentInjector,declarationEl);
}
class _View_DoChat2 extends import3.AppView<any> {
  _el_0:any;
  _ColorGenerator_0_3:import44.ColorGenerator;
  _TextImage_0_4:import45.Wrapper_TextImage;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoChat2,renderType_DoChat,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'text-img',(null as any));
    this._ColorGenerator_0_3 = new import44.ColorGenerator();
    this._TextImage_0_4 = new import45.Wrapper_TextImage(new import27.ElementRef(this._el_0),this._ColorGenerator_0_3);
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.ColorGenerator) && (0 === requestNodeIndex))) { return this._ColorGenerator_0_3; }
    if (((token === import46.TextImage) && (0 === requestNodeIndex))) { return this._TextImage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.convTitleText;
    this._TextImage_0_4.check_text(currVal_0,throwOnChange,false);
    this._TextImage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoChat2(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoChat2(viewUtils,parentInjector,declarationEl);
}
class _View_DoChat3 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _DoMssageItem_0_4:import47.Wrapper_DoMssageItem;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoChat3,renderType_DoChat,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'message-item',(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import47.viewFactory_DoMssageItem0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DoMssageItem_0_4 = new import47.Wrapper_DoMssageItem();
    this._appEl_0.initComponent(this._DoMssageItem_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DoMssageItem_0_4.context,([] as any[]),(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.DoMssageItem) && (0 === requestNodeIndex))) { return this._DoMssageItem_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    this._DoMssageItem_0_4.check_message(currVal_0,throwOnChange,false);
    this._DoMssageItem_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoChat3(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoChat3(viewUtils,parentInjector,declarationEl);
}
class _View_DoChat4 extends import3.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import5.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.Wrapper_NgIf;
  _text_3:any;
  _pipe_strEquals_0_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoChat4,renderType_DoChat,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import5.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import32.TemplateRef_(this._appEl_2,viewFactory_DoChat5);
    this._NgIf_2_6 = new import18.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._pipe_strEquals_0_0 = import2.pureProxy2((<_View_DoChat0>this.parent)._pipe_strEquals_0.transform.bind((<_View_DoChat0>this.parent)._pipe_strEquals_0));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import35.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_0:any = valUnwrapper.unwrap(import2.castByValue(this._pipe_strEquals_0_0,(<_View_DoChat0>this.parent)._pipe_strEquals_0.transform)(this.context.$implicit.op,'typing'));
    this._NgIf_2_6.check_ngIf(currVal_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgIf_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoChat4(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoChat4(viewUtils,parentInjector,declarationEl);
}
class _View_DoChat5 extends import3.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import5.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.Wrapper_NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoChat5,renderType_DoChat,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import5.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import32.TemplateRef_(this._appEl_2,viewFactory_DoChat6);
    this._NgIf_2_6 = new import18.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','typing-indicator');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'span',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_8 = this.renderer.createElement(this._el_4,'span',(null as any));
    this._text_9 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_10 = this.renderer.createElement(this._el_4,'span',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import35.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:boolean = !this.parent.parent.context.isPrivate;
    this._NgIf_2_6.check_ngIf(currVal_0,throwOnChange,false);
    this._NgIf_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoChat5(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoChat5(viewUtils,parentInjector,declarationEl);
}
class _View_DoChat6 extends import3.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_DoChat6,renderType_DoChat,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','message-data');
    this._text_1 = this.renderer.createText(this._el_0,'\n					',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'span',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','message-data-name');
    this._el_3 = this.renderer.createElement(this._el_2,'i',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','fa fa-circle online');
    this._text_4 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._expr_0 = import1.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import2.interpolate(1,' ',this.parent.parent.context.$implicit.doFriend.getNameText(),'');
    if (import2.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_4,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DoChat6(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_DoChat6(viewUtils,parentInjector,declarationEl);
}