/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './do-chat';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import15 from '@angular/core/src/linker/component_factory';
export declare class Wrapper_DoChat {
    context: import0.DoChat;
    changed: boolean;
    _friendIds: any;
    _convId: any;
    _convName: any;
    constructor(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any);
    check_friendIds(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_convId(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_convName(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare const DoChatNgFactory: import15.ComponentFactory<import0.DoChat>;
export declare function viewFactory_DoChat0(viewUtils: import2.ViewUtils, parentInjector: import6.Injector, declarationEl: import5.AppElement): import3.AppView<import0.DoChat>;
